// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mdb

import (
	"database/sql"
)

type AdminDatatype struct {
	AdminDtID    int64          `json:"admin_dt_id"`
	AdminRouteID int64          `json:"admin_route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        string         `json:"label"`
	Type         string         `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

type AdminField struct {
	AdminFieldID int64          `json:"admin_field_id"`
	AdminRouteID int64          `json:"admin_route_id"`
	ParentID     int64          `json:"parent_id"`
	Label        interface{}    `json:"label"`
	Data         interface{}    `json:"data"`
	Type         interface{}    `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

type AdminRoute struct {
	AdminRouteID int64          `json:"admin_route_id"`
	Author       interface{}    `json:"author"`
	AuthorID     interface{}    `json:"author_id"`
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Status       int64          `json:"status"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	Template     interface{}    `json:"template"`
}

type Datatype struct {
	DatatypeID   int64          `json:"datatype_id"`
	RouteID      int64          `json:"route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        string         `json:"label"`
	Type         string         `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

type Field struct {
	FieldID      int64          `json:"field_id"`
	RouteID      int64          `json:"route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        interface{}    `json:"label"`
	Data         interface{}    `json:"data"`
	Type         interface{}    `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

type Media struct {
	ID                 int64          `json:"id"`
	Name               sql.NullString `json:"name"`
	DisplayName        sql.NullString `json:"display_name"`
	Alt                sql.NullString `json:"alt"`
	Caption            sql.NullString `json:"caption"`
	Description        sql.NullString `json:"description"`
	Class              sql.NullString `json:"class"`
	Author             interface{}    `json:"author"`
	AuthorID           int64          `json:"author_id"`
	DateCreated        string         `json:"date_created"`
	DateModified       string         `json:"date_modified"`
	Url                sql.NullString `json:"url"`
	Mimetype           sql.NullString `json:"mimetype"`
	Dimensions         sql.NullString `json:"dimensions"`
	OptimizedMobile    sql.NullString `json:"optimized_mobile"`
	OptimizedTablet    sql.NullString `json:"optimized_tablet"`
	OptimizedDesktop   sql.NullString `json:"optimized_desktop"`
	OptimizedUltrawide sql.NullString `json:"optimized_ultrawide"`
}

type MediaDimension struct {
	ID     int64          `json:"id"`
	Label  sql.NullString `json:"label"`
	Width  sql.NullInt64  `json:"width"`
	Height sql.NullInt64  `json:"height"`
}

type Route struct {
	RouteID      int64          `json:"route_id"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Status       int64          `json:"status"`
	DateCreated  string         `json:"date_created"`
	DateModified string         `json:"date_modified"`
	Content      sql.NullString `json:"content"`
}

type Tables struct {
	ID    int64          `json:"id"`
	Label sql.NullString `json:"label"`
}

type Token struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	TokenType string       `json:"token_type"`
	Token     string       `json:"token"`
	IssuedAt  string       `json:"issued_at"`
	ExpiresAt string       `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
}

type User struct {
	UserID       int64  `json:"user_id"`
	DateCreated  string `json:"date_created"`
	DateModified string `json:"date_modified"`
	Username     string `json:"username"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	Hash         string `json:"hash"`
	Role         string `json:"role"`
}
