// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package mdb

import (
	"context"
	"database/sql"
)

const checkAdminParentExists = `-- name: CheckAdminParentExists :one
SELECT EXISTS(SELECT 1 FROM admin_datatype WHERE admin_dt_id =?)
`

func (q *Queries) CheckAdminParentExists(ctx context.Context, adminDtID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAdminParentExists, adminDtID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkAdminRouteExists = `-- name: CheckAdminRouteExists :one
SELECT EXISTS(SELECT 1 FROM admin_route WHERE admin_route_id=?)
`

func (q *Queries) CheckAdminRouteExists(ctx context.Context, adminRouteID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAdminRouteExists, adminRouteID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkAuthorExists = `-- name: CheckAuthorExists :one
SELECT EXISTS(SELECT 1 FROM user WHERE username=?)
`

func (q *Queries) CheckAuthorExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAuthorExists, username)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkAuthorIdExists = `-- name: CheckAuthorIdExists :one
SELECT EXISTS(SELECT 1 FROM user WHERE user_id=?)
`

func (q *Queries) CheckAuthorIdExists(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAuthorIdExists, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkParentExists = `-- name: CheckParentExists :one
SELECT EXISTS(SELECT 1 FROM datatype WHERE datatype_id =?)
`

func (q *Queries) CheckParentExists(ctx context.Context, datatypeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkParentExists, datatypeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkRouteExists = `-- name: CheckRouteExists :one
SELECT EXISTS(SELECT 1 FROM route WHERE route_id=?)
`

func (q *Queries) CheckRouteExists(ctx context.Context, routeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkRouteExists, routeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAdminDatatype = `-- name: CountAdminDatatype :one
SELECT COUNT(*)
FROM admin_datatype
`

func (q *Queries) CountAdminDatatype(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminDatatype)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminField = `-- name: CountAdminField :one
SELECT COUNT(*)
FROM admin_field
`

func (q *Queries) CountAdminField(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminField)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminroute = `-- name: CountAdminroute :one
SELECT COUNT(*)
FROM admin_route
`

func (q *Queries) CountAdminroute(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminroute)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDatatype = `-- name: CountDatatype :one
SELECT COUNT(*)
FROM datatype
`

func (q *Queries) CountDatatype(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDatatype)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countField = `-- name: CountField :one
SELECT COUNT(*)
FROM field
`

func (q *Queries) CountField(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countField)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMD = `-- name: CountMD :one
SELECT COUNT(*)
FROM media_dimension
`

func (q *Queries) CountMD(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMD)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMedia = `-- name: CountMedia :one
SELECT COUNT(*)
FROM media
`

func (q *Queries) CountMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoute = `-- name: CountRoute :one
SELECT COUNT(*)
FROM route
`

func (q *Queries) CountRoute(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoute)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTables = `-- name: CountTables :one
SELECT COUNT(*)
FROM tables
`

func (q *Queries) CountTables(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTables)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTokens = `-- name: CountTokens :one
SELECT COUNT(*)
FROM token
`

func (q *Queries) CountTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM user
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminDatatype = `-- name: CreateAdminDatatype :one
INSERT INTO admin_datatype (
    admin_route_id,
    parent_id,
    label,
    type,
    author,
    author_id,
    date_created,
    date_modified
    ) VALUES (
  ?, ?,?, ?,?, ?,?,?
    ) RETURNING admin_dt_id, admin_route_id, parent_id, label, type, author, author_id, date_created, date_modified
`

type CreateAdminDatatypeParams struct {
	AdminRouteID int64          `json:"admin_route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        string         `json:"label"`
	Type         string         `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

func (q *Queries) CreateAdminDatatype(ctx context.Context, arg CreateAdminDatatypeParams) (AdminDatatype, error) {
	row := q.db.QueryRowContext(ctx, createAdminDatatype,
		arg.AdminRouteID,
		arg.ParentID,
		arg.Label,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
	)
	var i AdminDatatype
	err := row.Scan(
		&i.AdminDtID,
		&i.AdminRouteID,
		&i.ParentID,
		&i.Label,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const createAdminField = `-- name: CreateAdminField :one
INSERT INTO admin_field (
    admin_route_id,
    parent_id,
    label,
    data,
    type,
    author,
    author_id,
    date_created,
    date_modified
    ) VALUES (
?,?, ?,?, ?, ?,?, ?,?
    ) RETURNING admin_field_id, admin_route_id, parent_id, label, data, type, author, author_id, date_created, date_modified
`

type CreateAdminFieldParams struct {
	AdminRouteID int64          `json:"admin_route_id"`
	ParentID     int64          `json:"parent_id"`
	Label        interface{}    `json:"label"`
	Data         interface{}    `json:"data"`
	Type         interface{}    `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

func (q *Queries) CreateAdminField(ctx context.Context, arg CreateAdminFieldParams) (AdminField, error) {
	row := q.db.QueryRowContext(ctx, createAdminField,
		arg.AdminRouteID,
		arg.ParentID,
		arg.Label,
		arg.Data,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
	)
	var i AdminField
	err := row.Scan(
		&i.AdminFieldID,
		&i.AdminRouteID,
		&i.ParentID,
		&i.Label,
		&i.Data,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const createAdminRoute = `-- name: CreateAdminRoute :one
INSERT INTO admin_route (
author,
author_id,
slug,
title,
status,
date_created,
date_modified,
template
) VALUES (
?,?,?,?,?,?,?,?
) RETURNING admin_route_id, author, author_id, slug, title, status, date_created, date_modified, template
`

type CreateAdminRouteParams struct {
	Author       interface{}    `json:"author"`
	AuthorID     interface{}    `json:"author_id"`
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Status       int64          `json:"status"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	Template     interface{}    `json:"template"`
}

func (q *Queries) CreateAdminRoute(ctx context.Context, arg CreateAdminRouteParams) (AdminRoute, error) {
	row := q.db.QueryRowContext(ctx, createAdminRoute,
		arg.Author,
		arg.AuthorID,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.DateCreated,
		arg.DateModified,
		arg.Template,
	)
	var i AdminRoute
	err := row.Scan(
		&i.AdminRouteID,
		&i.Author,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.DateCreated,
		&i.DateModified,
		&i.Template,
	)
	return i, err
}

const createDatatype = `-- name: CreateDatatype :one
INSERT INTO datatype (
    route_id,
    parent_id,
    label,
    type,
    author,
    author_id,
    date_created,
    date_modified
    ) VALUES (
  ?, ?,?, ?,?, ?,?,?
    ) RETURNING datatype_id, route_id, parent_id, label, type, author, author_id, date_created, date_modified
`

type CreateDatatypeParams struct {
	RouteID      int64          `json:"route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        string         `json:"label"`
	Type         string         `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

func (q *Queries) CreateDatatype(ctx context.Context, arg CreateDatatypeParams) (Datatype, error) {
	row := q.db.QueryRowContext(ctx, createDatatype,
		arg.RouteID,
		arg.ParentID,
		arg.Label,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
	)
	var i Datatype
	err := row.Scan(
		&i.DatatypeID,
		&i.RouteID,
		&i.ParentID,
		&i.Label,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const createField = `-- name: CreateField :one
INSERT INTO field (
    route_id,
    parent_id,
    label,
    data,
    type,
    author,
    author_id,
    date_created,
    date_modified
    ) VALUES (
?,?, ?,?, ?, ?,?, ?,?
    ) RETURNING field_id, route_id, parent_id, label, data, type, author, author_id, date_created, date_modified
`

type CreateFieldParams struct {
	RouteID      int64          `json:"route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        interface{}    `json:"label"`
	Data         interface{}    `json:"data"`
	Type         interface{}    `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (Field, error) {
	row := q.db.QueryRowContext(ctx, createField,
		arg.RouteID,
		arg.ParentID,
		arg.Label,
		arg.Data,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
	)
	var i Field
	err := row.Scan(
		&i.FieldID,
		&i.RouteID,
		&i.ParentID,
		&i.Label,
		&i.Data,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    name,
    display_name,
    alt,
    caption,
    description,
    class,
    author,
    author_id,
    date_created,
    date_modified,
    url,
    mimetype,
    dimensions,
    optimized_mobile,
    optimized_tablet,
    optimized_desktop,
    optimized_ultrawide
) VALUES (
 ?,?,? ,?,?,? ,?,?,? ,?,?,? ,?,?,? ,?,?
)
RETURNING id, name, display_name, alt, caption, description, class, author, author_id, date_created, date_modified, url, mimetype, dimensions, optimized_mobile, optimized_tablet, optimized_desktop, optimized_ultrawide
`

type CreateMediaParams struct {
	Name               sql.NullString `json:"name"`
	DisplayName        sql.NullString `json:"display_name"`
	Alt                sql.NullString `json:"alt"`
	Caption            sql.NullString `json:"caption"`
	Description        sql.NullString `json:"description"`
	Class              sql.NullString `json:"class"`
	Author             interface{}    `json:"author"`
	AuthorID           int64          `json:"author_id"`
	DateCreated        string         `json:"date_created"`
	DateModified       string         `json:"date_modified"`
	Url                sql.NullString `json:"url"`
	Mimetype           sql.NullString `json:"mimetype"`
	Dimensions         sql.NullString `json:"dimensions"`
	OptimizedMobile    sql.NullString `json:"optimized_mobile"`
	OptimizedTablet    sql.NullString `json:"optimized_tablet"`
	OptimizedDesktop   sql.NullString `json:"optimized_desktop"`
	OptimizedUltrawide sql.NullString `json:"optimized_ultrawide"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Name,
		arg.DisplayName,
		arg.Alt,
		arg.Caption,
		arg.Description,
		arg.Class,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.Url,
		arg.Mimetype,
		arg.Dimensions,
		arg.OptimizedMobile,
		arg.OptimizedTablet,
		arg.OptimizedDesktop,
		arg.OptimizedUltrawide,
	)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Alt,
		&i.Caption,
		&i.Description,
		&i.Class,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
		&i.Url,
		&i.Mimetype,
		&i.Dimensions,
		&i.OptimizedMobile,
		&i.OptimizedTablet,
		&i.OptimizedDesktop,
		&i.OptimizedUltrawide,
	)
	return i, err
}

const createMediaDimension = `-- name: CreateMediaDimension :one
INSERT INTO media_dimension(
    label,
    width,
    height
) VALUES (
  ?, ?, ?
)
RETURNING id, label, width, height
`

type CreateMediaDimensionParams struct {
	Label  sql.NullString `json:"label"`
	Width  sql.NullInt64  `json:"width"`
	Height sql.NullInt64  `json:"height"`
}

func (q *Queries) CreateMediaDimension(ctx context.Context, arg CreateMediaDimensionParams) (MediaDimension, error) {
	row := q.db.QueryRowContext(ctx, createMediaDimension, arg.Label, arg.Width, arg.Height)
	var i MediaDimension
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO route (
author,
author_id,
slug,
title,
status,
date_created,
date_modified, 
content
) VALUES (
?,?,?,?,?,?,?,?
) RETURNING route_id, author, author_id, slug, title, status, date_created, date_modified, content
`

type CreateRouteParams struct {
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Status       int64          `json:"status"`
	DateCreated  string         `json:"date_created"`
	DateModified string         `json:"date_modified"`
	Content      sql.NullString `json:"content"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.Author,
		arg.AuthorID,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.DateCreated,
		arg.DateModified,
		arg.Content,
	)
	var i Route
	err := row.Scan(
		&i.RouteID,
		&i.Author,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.DateCreated,
		&i.DateModified,
		&i.Content,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tables (
    label
) VALUES (
  ?
)
RETURNING id, label
`

func (q *Queries) CreateTable(ctx context.Context, label sql.NullString) (Tables, error) {
	row := q.db.QueryRowContext(ctx, createTable, label)
	var i Tables
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO token (
    user_id,
    token_type,
    token,
    issued_at,
    expires_at,
    revoked
    ) VALUES( 
    ?,?,?,?,?,?
    ) RETURNING id, user_id, token_type, token, issued_at, expires_at, revoked
`

type CreateTokenParams struct {
	UserID    int64        `json:"user_id"`
	TokenType string       `json:"token_type"`
	Token     string       `json:"token"`
	IssuedAt  string       `json:"issued_at"`
	ExpiresAt string       `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.UserID,
		arg.TokenType,
		arg.Token,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.Revoked,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenType,
		&i.Token,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
;

INSERT INTO user (
    date_created,
    date_modified,
    username,
    name,
    email ,
    hash,
    role
) VALUES (
?,?,?,?,?,?,?
)
RETURNING user_id, date_created, date_modified, username, name, email, hash, role
`

type CreateUserParams struct {
	DateCreated  string `json:"date_created"`
	DateModified string `json:"date_modified"`
	Username     string `json:"username"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	Hash         string `json:"hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.DateCreated,
		arg.DateModified,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Hash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DateCreated,
		&i.DateModified,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Hash,
		&i.Role,
	)
	return i, err
}

const deleteAdminDatatype = `-- name: DeleteAdminDatatype :exec
DELETE FROM admin_datatype
WHERE admin_dt_id = ?
`

func (q *Queries) DeleteAdminDatatype(ctx context.Context, adminDtID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminDatatype, adminDtID)
	return err
}

const deleteAdminField = `-- name: DeleteAdminField :exec
DELETE FROM admin_field
WHERE admin_field_id = ?
`

func (q *Queries) DeleteAdminField(ctx context.Context, adminFieldID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminField, adminFieldID)
	return err
}

const deleteAdminRoute = `-- name: DeleteAdminRoute :exec
DELETE FROM admin_route
WHERE slug = ?
`

func (q *Queries) DeleteAdminRoute(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteAdminRoute, slug)
	return err
}

const deleteDatatype = `-- name: DeleteDatatype :exec
DELETE FROM datatype
WHERE datatype_id = ?
`

func (q *Queries) DeleteDatatype(ctx context.Context, datatypeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDatatype, datatypeID)
	return err
}

const deleteField = `-- name: DeleteField :exec
DELETE FROM field
WHERE field_id = ?
`

func (q *Queries) DeleteField(ctx context.Context, fieldID int64) error {
	_, err := q.db.ExecContext(ctx, deleteField, fieldID)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const deleteMediaDimension = `-- name: DeleteMediaDimension :exec
DELETE FROM media_dimension
WHERE id = ?
`

func (q *Queries) DeleteMediaDimension(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMediaDimension, id)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM route
WHERE slug = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, slug)
	return err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables
WHERE id = ?
`

func (q *Queries) DeleteTable(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTable, id)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM token
WHERE id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user
WHERE user_id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getAdminDatatype = `-- name: GetAdminDatatype :one
SELECT admin_dt_id, admin_route_id, parent_id, label, type, author, author_id, date_created, date_modified FROM admin_datatype
WHERE admin_dt_id = ? LIMIT 1
`

func (q *Queries) GetAdminDatatype(ctx context.Context, adminDtID int64) (AdminDatatype, error) {
	row := q.db.QueryRowContext(ctx, getAdminDatatype, adminDtID)
	var i AdminDatatype
	err := row.Scan(
		&i.AdminDtID,
		&i.AdminRouteID,
		&i.ParentID,
		&i.Label,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getAdminDatatypeId = `-- name: GetAdminDatatypeId :one
SELECT admin_dt_id FROM admin_datatype
WHERE admin_dt_id = ? LIMIT 1
`

func (q *Queries) GetAdminDatatypeId(ctx context.Context, adminDtID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAdminDatatypeId, adminDtID)
	var admin_dt_id int64
	err := row.Scan(&admin_dt_id)
	return admin_dt_id, err
}

const getAdminField = `-- name: GetAdminField :one
SELECT admin_field_id, admin_route_id, parent_id, label, data, type, author, author_id, date_created, date_modified FROM admin_field
WHERE admin_field_id = ? LIMIT 1
`

func (q *Queries) GetAdminField(ctx context.Context, adminFieldID int64) (AdminField, error) {
	row := q.db.QueryRowContext(ctx, getAdminField, adminFieldID)
	var i AdminField
	err := row.Scan(
		&i.AdminFieldID,
		&i.AdminRouteID,
		&i.ParentID,
		&i.Label,
		&i.Data,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getAdminFieldId = `-- name: GetAdminFieldId :one
SELECT admin_field_id FROM admin_field
WHERE admin_field_id = ? LIMIT 1
`

func (q *Queries) GetAdminFieldId(ctx context.Context, adminFieldID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAdminFieldId, adminFieldID)
	var admin_field_id int64
	err := row.Scan(&admin_field_id)
	return admin_field_id, err
}

const getAdminRouteById = `-- name: GetAdminRouteById :one
SELECT admin_route_id, author, author_id, slug, title, status, date_created, date_modified, template FROM admin_route
WHERE admin_route_id = ? LIMIT 1
`

func (q *Queries) GetAdminRouteById(ctx context.Context, adminRouteID int64) (AdminRoute, error) {
	row := q.db.QueryRowContext(ctx, getAdminRouteById, adminRouteID)
	var i AdminRoute
	err := row.Scan(
		&i.AdminRouteID,
		&i.Author,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.DateCreated,
		&i.DateModified,
		&i.Template,
	)
	return i, err
}

const getAdminRouteBySlug = `-- name: GetAdminRouteBySlug :one
SELECT admin_route_id, author, author_id, slug, title, status, date_created, date_modified, template FROM admin_route
WHERE slug = ? LIMIT 1
`

func (q *Queries) GetAdminRouteBySlug(ctx context.Context, slug string) (AdminRoute, error) {
	row := q.db.QueryRowContext(ctx, getAdminRouteBySlug, slug)
	var i AdminRoute
	err := row.Scan(
		&i.AdminRouteID,
		&i.Author,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.DateCreated,
		&i.DateModified,
		&i.Template,
	)
	return i, err
}

const getAdminRouteId = `-- name: GetAdminRouteId :one
SELECT admin_route_id FROM admin_route
WHERE slug = ? LIMIT 1
`

func (q *Queries) GetAdminRouteId(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAdminRouteId, slug)
	var admin_route_id int64
	err := row.Scan(&admin_route_id)
	return admin_route_id, err
}

const getDatatype = `-- name: GetDatatype :one
SELECT datatype_id, route_id, parent_id, label, type, author, author_id, date_created, date_modified FROM datatype
WHERE datatype_id = ? LIMIT 1
`

func (q *Queries) GetDatatype(ctx context.Context, datatypeID int64) (Datatype, error) {
	row := q.db.QueryRowContext(ctx, getDatatype, datatypeID)
	var i Datatype
	err := row.Scan(
		&i.DatatypeID,
		&i.RouteID,
		&i.ParentID,
		&i.Label,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getField = `-- name: GetField :one
SELECT field_id, route_id, parent_id, label, data, type, author, author_id, date_created, date_modified FROM field
WHERE field_id = ? LIMIT 1
`

func (q *Queries) GetField(ctx context.Context, fieldID int64) (Field, error) {
	row := q.db.QueryRowContext(ctx, getField, fieldID)
	var i Field
	err := row.Scan(
		&i.FieldID,
		&i.RouteID,
		&i.ParentID,
		&i.Label,
		&i.Data,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getGlobalAdminDatatypeId = `-- name: GetGlobalAdminDatatypeId :one
;

SELECT admin_dt_id, admin_route_id, parent_id, label, type, author, author_id, date_created, date_modified FROM admin_datatype
WHERE type = "GLOBAL" AND parent_id = NULL AND admin_route_id = NULL LIMIT 1
`

func (q *Queries) GetGlobalAdminDatatypeId(ctx context.Context) (AdminDatatype, error) {
	row := q.db.QueryRowContext(ctx, getGlobalAdminDatatypeId)
	var i AdminDatatype
	err := row.Scan(
		&i.AdminDtID,
		&i.AdminRouteID,
		&i.ParentID,
		&i.Label,
		&i.Type,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, name, display_name, alt, caption, description, class, author, author_id, date_created, date_modified, url, mimetype, dimensions, optimized_mobile, optimized_tablet, optimized_desktop, optimized_ultrawide FROM media
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (Media, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Alt,
		&i.Caption,
		&i.Description,
		&i.Class,
		&i.Author,
		&i.AuthorID,
		&i.DateCreated,
		&i.DateModified,
		&i.Url,
		&i.Mimetype,
		&i.Dimensions,
		&i.OptimizedMobile,
		&i.OptimizedTablet,
		&i.OptimizedDesktop,
		&i.OptimizedUltrawide,
	)
	return i, err
}

const getMediaDimension = `-- name: GetMediaDimension :one
SELECT id, label, width, height FROM media_dimension
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMediaDimension(ctx context.Context, id int64) (MediaDimension, error) {
	row := q.db.QueryRowContext(ctx, getMediaDimension, id)
	var i MediaDimension
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT route_id, author, author_id, slug, title, status, date_created, date_modified, content FROM route
WHERE slug = ? LIMIT 1
`

func (q *Queries) GetRoute(ctx context.Context, slug string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, slug)
	var i Route
	err := row.Scan(
		&i.RouteID,
		&i.Author,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.DateCreated,
		&i.DateModified,
		&i.Content,
	)
	return i, err
}

const getRouteId = `-- name: GetRouteId :one
SELECT route_id FROM route
WHERE slug = ? LIMIT 1
`

func (q *Queries) GetRouteId(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRouteId, slug)
	var route_id int64
	err := row.Scan(&route_id)
	return route_id, err
}

const getTable = `-- name: GetTable :one
SELECT id, label FROM tables
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTable(ctx context.Context, id int64) (Tables, error) {
	row := q.db.QueryRowContext(ctx, getTable, id)
	var i Tables
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const getTableId = `-- name: GetTableId :one
SELECT id FROM tables
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTableId(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTableId, id)
	err := row.Scan(&id)
	return id, err
}

const getToken = `-- name: GetToken :one
SELECT id, user_id, token_type, token, issued_at, expires_at, revoked FROM token
WHERE id = ? LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, id int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenType,
		&i.Token,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getTokenByUserId = `-- name: GetTokenByUserId :one
SELECT id, user_id, token_type, token, issued_at, expires_at, revoked FROM token
WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetTokenByUserId(ctx context.Context, userID int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByUserId, userID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenType,
		&i.Token,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, date_created, date_modified, username, name, email, hash, role FROM user
WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DateCreated,
		&i.DateModified,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Hash,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, date_created, date_modified, username, name, email, hash, role FROM user
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DateCreated,
		&i.DateModified,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Hash,
		&i.Role,
	)
	return i, err
}

const getUserId = `-- name: GetUserId :one
SELECT user_id FROM user
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserId(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserId, email)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const listAdminDatatype = `-- name: ListAdminDatatype :many
SELECT admin_dt_id, admin_route_id, parent_id, label, type, author, author_id, date_created, date_modified FROM admin_datatype
ORDER BY admin_dt_id
`

func (q *Queries) ListAdminDatatype(ctx context.Context) ([]AdminDatatype, error) {
	rows, err := q.db.QueryContext(ctx, listAdminDatatype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminDatatype
	for rows.Next() {
		var i AdminDatatype
		if err := rows.Scan(
			&i.AdminDtID,
			&i.AdminRouteID,
			&i.ParentID,
			&i.Label,
			&i.Type,
			&i.Author,
			&i.AuthorID,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminDatatypeByRouteId = `-- name: ListAdminDatatypeByRouteId :many
SELECT admin_dt_id, admin_route_id, parent_id, label, type
FROM admin_datatype
WHERE admin_route_id = ?
`

type ListAdminDatatypeByRouteIdRow struct {
	AdminDtID    int64         `json:"admin_dt_id"`
	AdminRouteID int64         `json:"admin_route_id"`
	ParentID     sql.NullInt64 `json:"parent_id"`
	Label        string        `json:"label"`
	Type         string        `json:"type"`
}

func (q *Queries) ListAdminDatatypeByRouteId(ctx context.Context, adminRouteID int64) ([]ListAdminDatatypeByRouteIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminDatatypeByRouteId, adminRouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminDatatypeByRouteIdRow
	for rows.Next() {
		var i ListAdminDatatypeByRouteIdRow
		if err := rows.Scan(
			&i.AdminDtID,
			&i.AdminRouteID,
			&i.ParentID,
			&i.Label,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminDatatypeChildren = `-- name: ListAdminDatatypeChildren :many
SELECT admin_dt_id, admin_route_id, parent_id, label, type, author, author_id, date_created, date_modified FROM admin_datatype
WHERE parent_id = ?
`

func (q *Queries) ListAdminDatatypeChildren(ctx context.Context, parentID sql.NullInt64) ([]AdminDatatype, error) {
	rows, err := q.db.QueryContext(ctx, listAdminDatatypeChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminDatatype
	for rows.Next() {
		var i AdminDatatype
		if err := rows.Scan(
			&i.AdminDtID,
			&i.AdminRouteID,
			&i.ParentID,
			&i.Label,
			&i.Type,
			&i.Author,
			&i.AuthorID,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminField = `-- name: ListAdminField :many
SELECT admin_field_id, admin_route_id, parent_id, label, data, type, author, author_id, date_created, date_modified FROM admin_field
ORDER BY admin_field_id
`

func (q *Queries) ListAdminField(ctx context.Context) ([]AdminField, error) {
	rows, err := q.db.QueryContext(ctx, listAdminField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminField
	for rows.Next() {
		var i AdminField
		if err := rows.Scan(
			&i.AdminFieldID,
			&i.AdminRouteID,
			&i.ParentID,
			&i.Label,
			&i.Data,
			&i.Type,
			&i.Author,
			&i.AuthorID,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminFieldByRouteId = `-- name: ListAdminFieldByRouteId :many
SELECT admin_field_id, admin_route_id, parent_id, label, data, type
FROM admin_field
WHERE admin_route_id = ?
`

type ListAdminFieldByRouteIdRow struct {
	AdminFieldID int64       `json:"admin_field_id"`
	AdminRouteID int64       `json:"admin_route_id"`
	ParentID     int64       `json:"parent_id"`
	Label        interface{} `json:"label"`
	Data         interface{} `json:"data"`
	Type         interface{} `json:"type"`
}

func (q *Queries) ListAdminFieldByRouteId(ctx context.Context, adminRouteID int64) ([]ListAdminFieldByRouteIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminFieldByRouteId, adminRouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminFieldByRouteIdRow
	for rows.Next() {
		var i ListAdminFieldByRouteIdRow
		if err := rows.Scan(
			&i.AdminFieldID,
			&i.AdminRouteID,
			&i.ParentID,
			&i.Label,
			&i.Data,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminRoute = `-- name: ListAdminRoute :many
SELECT admin_route_id, author, author_id, slug, title, status, date_created, date_modified, template FROM admin_route
ORDER BY slug
`

func (q *Queries) ListAdminRoute(ctx context.Context) ([]AdminRoute, error) {
	rows, err := q.db.QueryContext(ctx, listAdminRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminRoute
	for rows.Next() {
		var i AdminRoute
		if err := rows.Scan(
			&i.AdminRouteID,
			&i.Author,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.DateCreated,
			&i.DateModified,
			&i.Template,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatatype = `-- name: ListDatatype :many
SELECT datatype_id, route_id, parent_id, label, type, author, author_id, date_created, date_modified FROM datatype
ORDER BY datatype_id
`

func (q *Queries) ListDatatype(ctx context.Context) ([]Datatype, error) {
	rows, err := q.db.QueryContext(ctx, listDatatype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datatype
	for rows.Next() {
		var i Datatype
		if err := rows.Scan(
			&i.DatatypeID,
			&i.RouteID,
			&i.ParentID,
			&i.Label,
			&i.Type,
			&i.Author,
			&i.AuthorID,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatatypeByRouteId = `-- name: ListDatatypeByRouteId :many
SELECT datatype_id, route_id, parent_id, label, type
FROM datatype
WHERE route_id = ?
`

type ListDatatypeByRouteIdRow struct {
	DatatypeID int64         `json:"datatype_id"`
	RouteID    int64         `json:"route_id"`
	ParentID   sql.NullInt64 `json:"parent_id"`
	Label      string        `json:"label"`
	Type       string        `json:"type"`
}

func (q *Queries) ListDatatypeByRouteId(ctx context.Context, routeID int64) ([]ListDatatypeByRouteIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatatypeByRouteId, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDatatypeByRouteIdRow
	for rows.Next() {
		var i ListDatatypeByRouteIdRow
		if err := rows.Scan(
			&i.DatatypeID,
			&i.RouteID,
			&i.ParentID,
			&i.Label,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listField = `-- name: ListField :many
SELECT field_id, route_id, parent_id, label, data, type, author, author_id, date_created, date_modified FROM field
ORDER BY field_id
`

func (q *Queries) ListField(ctx context.Context) ([]Field, error) {
	rows, err := q.db.QueryContext(ctx, listField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Field
	for rows.Next() {
		var i Field
		if err := rows.Scan(
			&i.FieldID,
			&i.RouteID,
			&i.ParentID,
			&i.Label,
			&i.Data,
			&i.Type,
			&i.Author,
			&i.AuthorID,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldByRouteId = `-- name: ListFieldByRouteId :many
SELECT field_id, route_id, parent_id, label, data, type
FROM field
WHERE route_id = ?
`

type ListFieldByRouteIdRow struct {
	FieldID  int64         `json:"field_id"`
	RouteID  int64         `json:"route_id"`
	ParentID sql.NullInt64 `json:"parent_id"`
	Label    interface{}   `json:"label"`
	Data     interface{}   `json:"data"`
	Type     interface{}   `json:"type"`
}

func (q *Queries) ListFieldByRouteId(ctx context.Context, routeID int64) ([]ListFieldByRouteIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listFieldByRouteId, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldByRouteIdRow
	for rows.Next() {
		var i ListFieldByRouteIdRow
		if err := rows.Scan(
			&i.FieldID,
			&i.RouteID,
			&i.ParentID,
			&i.Label,
			&i.Data,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many
SELECT id, name, display_name, alt, caption, description, class, author, author_id, date_created, date_modified, url, mimetype, dimensions, optimized_mobile, optimized_tablet, optimized_desktop, optimized_ultrawide FROM media
ORDER BY name
`

func (q *Queries) ListMedia(ctx context.Context) ([]Media, error) {
	rows, err := q.db.QueryContext(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Media
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Alt,
			&i.Caption,
			&i.Description,
			&i.Class,
			&i.Author,
			&i.AuthorID,
			&i.DateCreated,
			&i.DateModified,
			&i.Url,
			&i.Mimetype,
			&i.Dimensions,
			&i.OptimizedMobile,
			&i.OptimizedTablet,
			&i.OptimizedDesktop,
			&i.OptimizedUltrawide,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaDimension = `-- name: ListMediaDimension :many
SELECT id, label, width, height FROM media_dimension 
ORDER BY label
`

func (q *Queries) ListMediaDimension(ctx context.Context) ([]MediaDimension, error) {
	rows, err := q.db.QueryContext(ctx, listMediaDimension)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaDimension
	for rows.Next() {
		var i MediaDimension
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoute = `-- name: ListRoute :many
SELECT route_id, author, author_id, slug, title, status, date_created, date_modified, content FROM route
ORDER BY slug
`

func (q *Queries) ListRoute(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.RouteID,
			&i.Author,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.DateCreated,
			&i.DateModified,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTable = `-- name: ListTable :many
SELECT id, label FROM tables 
ORDER BY label
`

func (q *Queries) ListTable(ctx context.Context) ([]Tables, error) {
	rows, err := q.db.QueryContext(ctx, listTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tables
	for rows.Next() {
		var i Tables
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUser = `-- name: ListUser :many
SELECT user_id, date_created, date_modified, username, name, email, hash, role FROM user 
ORDER BY user_id
`

func (q *Queries) ListUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.DateCreated,
			&i.DateModified,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.Hash,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminDatatype = `-- name: UpdateAdminDatatype :exec
UPDATE admin_datatype
set admin_route_id = ?,
    parent_id = ?,
    label = ?,
    type = ?,
    author = ?,
    author_id = ?,
    date_created = ?,
    date_modified = ?
    WHERE admin_dt_id = ?
    RETURNING admin_dt_id, admin_route_id, parent_id, label, type, author, author_id, date_created, date_modified
`

type UpdateAdminDatatypeParams struct {
	AdminRouteID int64          `json:"admin_route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        string         `json:"label"`
	Type         string         `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	AdminDtID    int64          `json:"admin_dt_id"`
}

func (q *Queries) UpdateAdminDatatype(ctx context.Context, arg UpdateAdminDatatypeParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminDatatype,
		arg.AdminRouteID,
		arg.ParentID,
		arg.Label,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.AdminDtID,
	)
	return err
}

const updateAdminField = `-- name: UpdateAdminField :exec
UPDATE admin_field
set admin_route_id = ?,
    parent_id = ?,
    label = ?,
    data = ?,
    type = ?,
    author = ?,
    author_id = ?,
    date_created = ?,
    date_modified = ?
    WHERE admin_field_id = ?
    RETURNING admin_field_id, admin_route_id, parent_id, label, data, type, author, author_id, date_created, date_modified
`

type UpdateAdminFieldParams struct {
	AdminRouteID int64          `json:"admin_route_id"`
	ParentID     int64          `json:"parent_id"`
	Label        interface{}    `json:"label"`
	Data         interface{}    `json:"data"`
	Type         interface{}    `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	AdminFieldID int64          `json:"admin_field_id"`
}

func (q *Queries) UpdateAdminField(ctx context.Context, arg UpdateAdminFieldParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminField,
		arg.AdminRouteID,
		arg.ParentID,
		arg.Label,
		arg.Data,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.AdminFieldID,
	)
	return err
}

const updateAdminRoute = `-- name: UpdateAdminRoute :exec
UPDATE admin_route
set slug = ?,
    title = ?,
    status = ?,
    author = ?,
    author_id = ?,
    date_created = ?,
    date_modified = ?,
    template = ?
    WHERE slug = ?
    RETURNING admin_route_id, author, author_id, slug, title, status, date_created, date_modified, template
`

type UpdateAdminRouteParams struct {
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Status       int64          `json:"status"`
	Author       interface{}    `json:"author"`
	AuthorID     interface{}    `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	Template     interface{}    `json:"template"`
	Slug_2       string         `json:"slug_2"`
}

func (q *Queries) UpdateAdminRoute(ctx context.Context, arg UpdateAdminRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminRoute,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.Template,
		arg.Slug_2,
	)
	return err
}

const updateDatatype = `-- name: UpdateDatatype :exec
UPDATE datatype
set route_id = ?,
    parent_id = ?,
    label = ?,
    type = ?,
    author = ?,
    author_id = ?,
    date_created = ?,
    date_modified = ?
    WHERE datatype_id = ?
    RETURNING datatype_id, route_id, parent_id, label, type, author, author_id, date_created, date_modified
`

type UpdateDatatypeParams struct {
	RouteID      int64          `json:"route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        string         `json:"label"`
	Type         string         `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	DatatypeID   int64          `json:"datatype_id"`
}

func (q *Queries) UpdateDatatype(ctx context.Context, arg UpdateDatatypeParams) error {
	_, err := q.db.ExecContext(ctx, updateDatatype,
		arg.RouteID,
		arg.ParentID,
		arg.Label,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.DatatypeID,
	)
	return err
}

const updateField = `-- name: UpdateField :exec
UPDATE field
set route_id = ?,
    parent_id = ?,
    label = ?,
    data = ?,
    type = ?,
    author = ?,
    author_id = ?,
    date_created = ?,
    date_modified = ?
    WHERE field_id = ?
    RETURNING field_id, route_id, parent_id, label, data, type, author, author_id, date_created, date_modified
`

type UpdateFieldParams struct {
	RouteID      int64          `json:"route_id"`
	ParentID     sql.NullInt64  `json:"parent_id"`
	Label        interface{}    `json:"label"`
	Data         interface{}    `json:"data"`
	Type         interface{}    `json:"type"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  sql.NullString `json:"date_created"`
	DateModified sql.NullString `json:"date_modified"`
	FieldID      int64          `json:"field_id"`
}

func (q *Queries) UpdateField(ctx context.Context, arg UpdateFieldParams) error {
	_, err := q.db.ExecContext(ctx, updateField,
		arg.RouteID,
		arg.ParentID,
		arg.Label,
		arg.Data,
		arg.Type,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.FieldID,
	)
	return err
}

const updateMedia = `-- name: UpdateMedia :exec
UPDATE media
  set   name = ?,
        display_name = ?,
        alt = ?,
        caption = ?,
        description = ?,
        class = ?,
        author = ?,
        author_id = ?,
        date_created = ?,
        date_modified = ?,
        url = ?,
        mimetype = ?,
        dimensions = ?,
        optimized_mobile = ?,
        optimized_tablet = ?,
        optimized_desktop = ?,
        optimized_ultrawide = ?
        WHERE id = ?
`

type UpdateMediaParams struct {
	Name               sql.NullString `json:"name"`
	DisplayName        sql.NullString `json:"display_name"`
	Alt                sql.NullString `json:"alt"`
	Caption            sql.NullString `json:"caption"`
	Description        sql.NullString `json:"description"`
	Class              sql.NullString `json:"class"`
	Author             interface{}    `json:"author"`
	AuthorID           int64          `json:"author_id"`
	DateCreated        string         `json:"date_created"`
	DateModified       string         `json:"date_modified"`
	Url                sql.NullString `json:"url"`
	Mimetype           sql.NullString `json:"mimetype"`
	Dimensions         sql.NullString `json:"dimensions"`
	OptimizedMobile    sql.NullString `json:"optimized_mobile"`
	OptimizedTablet    sql.NullString `json:"optimized_tablet"`
	OptimizedDesktop   sql.NullString `json:"optimized_desktop"`
	OptimizedUltrawide sql.NullString `json:"optimized_ultrawide"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateMedia,
		arg.Name,
		arg.DisplayName,
		arg.Alt,
		arg.Caption,
		arg.Description,
		arg.Class,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.Url,
		arg.Mimetype,
		arg.Dimensions,
		arg.OptimizedMobile,
		arg.OptimizedTablet,
		arg.OptimizedDesktop,
		arg.OptimizedUltrawide,
		arg.ID,
	)
	return err
}

const updateMediaDimension = `-- name: UpdateMediaDimension :exec
UPDATE media_dimension
set label = ?,
    width = ?,
    height = ? 
WHERE id = ?
`

type UpdateMediaDimensionParams struct {
	Label  sql.NullString `json:"label"`
	Width  sql.NullInt64  `json:"width"`
	Height sql.NullInt64  `json:"height"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateMediaDimension(ctx context.Context, arg UpdateMediaDimensionParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaDimension,
		arg.Label,
		arg.Width,
		arg.Height,
		arg.ID,
	)
	return err
}

const updateRoute = `-- name: UpdateRoute :exec
UPDATE route
set slug = ?,
    title = ?,
    status = ?,
    content = ?, 
    author = ?,
    author_id = ?,
    date_created = ?,
    date_modified = ?
    WHERE slug = ?
    RETURNING route_id, author, author_id, slug, title, status, date_created, date_modified, content
`

type UpdateRouteParams struct {
	Slug         string         `json:"slug"`
	Title        string         `json:"title"`
	Status       int64          `json:"status"`
	Content      sql.NullString `json:"content"`
	Author       interface{}    `json:"author"`
	AuthorID     int64          `json:"author_id"`
	DateCreated  string         `json:"date_created"`
	DateModified string         `json:"date_modified"`
	Slug_2       string         `json:"slug_2"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateRoute,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.Content,
		arg.Author,
		arg.AuthorID,
		arg.DateCreated,
		arg.DateModified,
		arg.Slug_2,
	)
	return err
}

const updateTable = `-- name: UpdateTable :exec
UPDATE tables
set label = ?
WHERE id = ?
`

type UpdateTableParams struct {
	Label sql.NullString `json:"label"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) error {
	_, err := q.db.ExecContext(ctx, updateTable, arg.Label, arg.ID)
	return err
}

const updateToken = `-- name: UpdateToken :exec
UPDATE token
set token = ?,
issued_at = ?,
expires_at= ?,
revoked = ?
WHERE id = ?
`

type UpdateTokenParams struct {
	Token     string       `json:"token"`
	IssuedAt  string       `json:"issued_at"`
	ExpiresAt string       `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken,
		arg.Token,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.Revoked,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user
set date_created = ?,
    date_modified = ?,
    username = ?,
    name = ?,
    email = ?,
    hash = ?,
    role = ?
WHERE user_id = ?
`

type UpdateUserParams struct {
	DateCreated  string `json:"date_created"`
	DateModified string `json:"date_modified"`
	Username     string `json:"username"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	Hash         string `json:"hash"`
	Role         string `json:"role"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.DateCreated,
		arg.DateModified,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Hash,
		arg.Role,
		arg.UserID,
	)
	return err
}

const utilityGetAdminDatatypes = `-- name: UtilityGetAdminDatatypes :many
select admin_dt_id, label from admin_datatype
`

type UtilityGetAdminDatatypesRow struct {
	AdminDtID int64  `json:"admin_dt_id"`
	Label     string `json:"label"`
}

func (q *Queries) UtilityGetAdminDatatypes(ctx context.Context) ([]UtilityGetAdminDatatypesRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetAdminDatatypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetAdminDatatypesRow
	for rows.Next() {
		var i UtilityGetAdminDatatypesRow
		if err := rows.Scan(&i.AdminDtID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetAdminRoutes = `-- name: UtilityGetAdminRoutes :many
select admin_route_id, slug from admin_route
`

type UtilityGetAdminRoutesRow struct {
	AdminRouteID int64  `json:"admin_route_id"`
	Slug         string `json:"slug"`
}

func (q *Queries) UtilityGetAdminRoutes(ctx context.Context) ([]UtilityGetAdminRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetAdminRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetAdminRoutesRow
	for rows.Next() {
		var i UtilityGetAdminRoutesRow
		if err := rows.Scan(&i.AdminRouteID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetAdminfields = `-- name: UtilityGetAdminfields :many
select admin_field_id, label from admin_field
`

type UtilityGetAdminfieldsRow struct {
	AdminFieldID int64       `json:"admin_field_id"`
	Label        interface{} `json:"label"`
}

func (q *Queries) UtilityGetAdminfields(ctx context.Context) ([]UtilityGetAdminfieldsRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetAdminfields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetAdminfieldsRow
	for rows.Next() {
		var i UtilityGetAdminfieldsRow
		if err := rows.Scan(&i.AdminFieldID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetDatatypes = `-- name: UtilityGetDatatypes :many
select datatype_id, label from datatype
`

type UtilityGetDatatypesRow struct {
	DatatypeID int64  `json:"datatype_id"`
	Label      string `json:"label"`
}

func (q *Queries) UtilityGetDatatypes(ctx context.Context) ([]UtilityGetDatatypesRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetDatatypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetDatatypesRow
	for rows.Next() {
		var i UtilityGetDatatypesRow
		if err := rows.Scan(&i.DatatypeID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetFields = `-- name: UtilityGetFields :many
select field_id, label from field
`

type UtilityGetFieldsRow struct {
	FieldID int64       `json:"field_id"`
	Label   interface{} `json:"label"`
}

func (q *Queries) UtilityGetFields(ctx context.Context) ([]UtilityGetFieldsRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetFieldsRow
	for rows.Next() {
		var i UtilityGetFieldsRow
		if err := rows.Scan(&i.FieldID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetMedia = `-- name: UtilityGetMedia :many
select id, name from media
`

type UtilityGetMediaRow struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) UtilityGetMedia(ctx context.Context) ([]UtilityGetMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetMediaRow
	for rows.Next() {
		var i UtilityGetMediaRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetMediaDimension = `-- name: UtilityGetMediaDimension :many
select id, label from media_dimension
`

type UtilityGetMediaDimensionRow struct {
	ID    int64          `json:"id"`
	Label sql.NullString `json:"label"`
}

func (q *Queries) UtilityGetMediaDimension(ctx context.Context) ([]UtilityGetMediaDimensionRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetMediaDimension)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetMediaDimensionRow
	for rows.Next() {
		var i UtilityGetMediaDimensionRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetRoute = `-- name: UtilityGetRoute :many
select route_id, slug from route
`

type UtilityGetRouteRow struct {
	RouteID int64  `json:"route_id"`
	Slug    string `json:"slug"`
}

func (q *Queries) UtilityGetRoute(ctx context.Context) ([]UtilityGetRouteRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetRouteRow
	for rows.Next() {
		var i UtilityGetRouteRow
		if err := rows.Scan(&i.RouteID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetTables = `-- name: UtilityGetTables :many
select id, label from tables
`

func (q *Queries) UtilityGetTables(ctx context.Context) ([]Tables, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tables
	for rows.Next() {
		var i Tables
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetToken = `-- name: UtilityGetToken :many
select id, user_id  from token
`

type UtilityGetTokenRow struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UtilityGetToken(ctx context.Context) ([]UtilityGetTokenRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetTokenRow
	for rows.Next() {
		var i UtilityGetTokenRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityGetUsers = `-- name: UtilityGetUsers :many
select user_id, username from user
`

type UtilityGetUsersRow struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) UtilityGetUsers(ctx context.Context) ([]UtilityGetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityGetUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityGetUsersRow
	for rows.Next() {
		var i UtilityGetUsersRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const utilityRecordCount = `-- name: UtilityRecordCount :many
SELECT 'admin_datatype' AS table_name, COUNT(*) AS row_count FROM admin_datatype
UNION ALL
SELECT 'admin_field' AS table_name, COUNT(*) AS row_count FROM admin_field
UNION ALL
SELECT 'admin_route' AS table_name, COUNT(*) AS row_count FROM admin_route
UNION ALL
SELECT 'datatype' AS table_name, COUNT(*) AS row_count FROM datatype
UNION ALL
SELECT 'field' AS table_name, COUNT(*) AS row_count FROM field
UNION ALL
SELECT 'route' AS table_name, COUNT(*) AS row_count FROM route
UNION ALL
SELECT 'media' AS table_name, COUNT(*) AS row_count FROM media
UNION ALL
SELECT 'media_dimension' AS table_name, COUNT(*) AS row_count FROM media_dimension
UNION ALL
SELECT 'tables' AS table_name, COUNT(*) AS row_count FROM tables
UNION ALL
SELECT 'token' AS table_name, COUNT(*) AS row_count FROM token
UNION ALL
SELECT 'user' AS table_name, COUNT(*) AS row_count FROM user
`

type UtilityRecordCountRow struct {
	TableName string `json:"table_name"`
	RowCount  int64  `json:"row_count"`
}

func (q *Queries) UtilityRecordCount(ctx context.Context) ([]UtilityRecordCountRow, error) {
	rows, err := q.db.QueryContext(ctx, utilityRecordCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UtilityRecordCountRow
	for rows.Next() {
		var i UtilityRecordCountRow
		if err := rows.Scan(&i.TableName, &i.RowCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
