CREATE TABLE datatype (
    id INTEGER PRIMARY KEY,
    routeid INTEGER DEFAULT NULL,
    parentid INTEGER DEFAULT NULL,
    label TEXT NOT NULL,
    type TEXT NOT NULL,
    struct TEXT DEFAULT NULL,
    author TEXT NOT NULL DEFAULT "system",
    authorid INTEGER NOT NULL DEFAULT "0",
    datecreated TEXT  DEFAULT LOCALTIMESTAMP, 
    datemodified TEXT DEFAULT LOCALTIMESTAMP,
    FOREIGN KEY (author) REFERENCES user(username) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (authorid) REFERENCES user(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (routeid) REFERENCES adminroute(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (parentid) REFERENCES field(id) ON DELETE SET DEFAULT ON UPDATE CASCADE
);
