CREATE TABLE datatype (
    datatype_id INTEGER PRIMARY KEY,
    routeid INTEGER NOT NULL DEFAULT 1,
    parentid INTEGER DEFAULT NULL,
    label TEXT NOT NULL,
    type TEXT NOT NULL,
    author TEXT NOT NULL DEFAULT "system",
    authorid INTEGER NOT NULL DEFAULT 1,
    datecreated TEXT  DEFAULT LOCALTIMESTAMP, 
    datemodified TEXT DEFAULT LOCALTIMESTAMP,
    FOREIGN KEY (author) REFERENCES user(username) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (authorid) REFERENCES user(user_id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (routeid) REFERENCES route(route_id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (parentid) REFERENCES datatype(datatype_id) ON DELETE SET DEFAULT ON UPDATE CASCADE
);
