select * from attributes;
select * from elements;
select * from fields;
select * from routes;
select * from adminroutes;
select * from users;
select * from media_dimensions;
select * from media;
select * from tables;
