CREATE TABLE IF NOT EXISTS tables (
    id TEXT PRIMARY KEY NOT NULL,
    label TEXT NOT NULL
        UNIQUE,
    author_id TEXT
        REFERENCES users
            ON UPDATE CASCADE ON DELETE SET NULL
);
