CREATE TABLE IF NOT EXISTS tokens (
    id VARCHAR(26) PRIMARY KEY NOT NULL,
    user_id VARCHAR(26) NOT NULL,
    token_type VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    expires_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked TINYINT(1) DEFAULT 0 NOT NULL,
    CONSTRAINT token
        UNIQUE (token),
    CONSTRAINT fk_tokens_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
            ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_tokens_user ON tokens(user_id);
