DROP TABLE IF EXISTS admin_datatype;
DROP TABLE IF EXISTS admin_field;
DROP TABLE IF EXISTS adminroute;
DROP TABLE IF EXISTS datatype;
DROP TABLE IF EXISTS field;
DROP TABLE IF EXISTS route;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS media_dimension;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS user;

