CREATE TABLE field (
    id INTEGER PRIMARY KEY,
    routeid INTEGER ,
    parentid INTEGER ,
    label TEXT NOT NULL DEFAULT "unlabeled",
    data TEXT NOT NULL DEFAULT "",
    type TEXT NOT NULL DEFAULT "text",
    struct TEXT DEFAULT NULL,
    author TEXT NOT NULL DEFAULT "system",
    authorid INTEGER NOT NULL DEFAULT 1,
    datecreated TEXT NOT NULL DEFAULT LOCALTIMESTAMP,
    datemodified TEXT DEFAULT LOCALTIMESTAMP,
    FOREIGN KEY (author) REFERENCES user(username) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (authorid) REFERENCES user(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (routeid) REFERENCES adminroute(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (parentid) REFERENCES datatype(id) ON DELETE CASCADE ON UPDATE CASCADE
);
