package main

// Entities defines all entity configurations for code generation.
var Entities = []Entity{
	// ========================
	// FULL GENERATION ENTITIES
	// ========================

	// Users
	{
		Name:               "Users",
		Singular:           "User",
		Plural:             "Users",
		SqlcTypeName:       "Users",
		TableName:          "users",
		IDType:             "types.UserID",
		IDField:            "UserID",
		NewIDFunc:          "types.NewUserID()",
		UpdateSuccessField: "s.Username",
		Fields: []Field{
			{AppName: "UserID", Type: "types.UserID", JSONTag: "user_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "Username", Type: "string", JSONTag: "username", InCreate: true, InUpdate: true},
			{AppName: "Name", Type: "string", JSONTag: "name", InCreate: true, InUpdate: true},
			{AppName: "Email", Type: "types.Email", JSONTag: "email", InCreate: true, InUpdate: true},
			{AppName: "Hash", Type: "string", JSONTag: "hash", InCreate: true, InUpdate: true},
			{AppName: "Role", SqlcName: "Roles", Type: "string", JSONTag: "role", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "user_gen.go",
	},

	// Media
	{
		Name:               "Media",
		Singular:           "Media",
		Plural:             "Media",
		SqlcTypeName:       "Media",
		TableName:          "media",
		IDType:             "types.MediaID",
		IDField:            "MediaID",
		NewIDFunc:          "types.NewMediaID()",
		HasPaginated:       true,
		UpdateSuccessField: "s.MediaID",
		Fields: []Field{
			{AppName: "MediaID", Type: "types.MediaID", JSONTag: "media_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "Name", Type: "sql.NullString", JSONTag: "name", InCreate: true, InUpdate: true},
			{AppName: "DisplayName", Type: "sql.NullString", JSONTag: "display_name", InCreate: true, InUpdate: true},
			{AppName: "Alt", Type: "sql.NullString", JSONTag: "alt", InCreate: true, InUpdate: true},
			{AppName: "Caption", Type: "sql.NullString", JSONTag: "caption", InCreate: true, InUpdate: true},
			{AppName: "Description", Type: "sql.NullString", JSONTag: "description", InCreate: true, InUpdate: true},
			{AppName: "Class", Type: "sql.NullString", JSONTag: "class", InCreate: true, InUpdate: true},
			{AppName: "Mimetype", Type: "sql.NullString", JSONTag: "mimetype", InCreate: true, InUpdate: true},
			{AppName: "Dimensions", Type: "sql.NullString", JSONTag: "dimensions", InCreate: true, InUpdate: true},
			{AppName: "URL", Type: "types.URL", JSONTag: "url", InCreate: true, InUpdate: true},
			{AppName: "Srcset", Type: "sql.NullString", JSONTag: "srcset", InCreate: true, InUpdate: true},
			{AppName: "FocalX", Type: "types.NullableFloat64", JSONTag: "focal_x", InCreate: true, InUpdate: true},
			{AppName: "FocalY", Type: "types.NullableFloat64", JSONTag: "focal_y", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "media_gen.go",
	},

	// Tables
	{
		Name:                "Tables",
		Singular:            "Table",
		Plural:              "Tables",
		SqlcTypeName:        "Tables",
		TableName:           "tables",
		IDType:              "string",
		IDField:             "ID",
		NewIDFunc:           "string(types.NewTableID())",
		UpdateSuccessField:  "s.ID",
		SqlcCreateTableName: "CreateTablesTable",
		SqlcCountName:       "CountTables",
		Fields: []Field{
			{AppName: "ID", Type: "string", JSONTag: "id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: false, InUpdate: false},
		},
		OutputFile: "table_gen.go",
	},

	// ContentData
	{
		Name:               "ContentData",
		Singular:           "ContentData",
		Plural:             "ContentData",
		SqlcTypeName:       "ContentData",
		TableName:          "content_data",
		IDType:             "types.ContentID",
		IDField:            "ContentDataID",
		NewIDFunc:          "types.NewContentID()",
		HasPaginated:       true,
		UpdateSuccessField: "s.ContentDataID",
		Fields: []Field{
			{AppName: "ContentDataID", Type: "types.ContentID", JSONTag: "content_data_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "ParentID", Type: "types.NullableContentID", JSONTag: "parent_id", InCreate: true, InUpdate: true},
			{AppName: "FirstChildID", Type: "types.NullableContentID", JSONTag: "first_child_id", InCreate: true, InUpdate: true},
			{AppName: "NextSiblingID", Type: "types.NullableContentID", JSONTag: "next_sibling_id", InCreate: true, InUpdate: true},
			{AppName: "PrevSiblingID", Type: "types.NullableContentID", JSONTag: "prev_sibling_id", InCreate: true, InUpdate: true},
			{AppName: "RouteID", Type: "types.NullableRouteID", JSONTag: "route_id", InCreate: true, InUpdate: true},
			{AppName: "DatatypeID", Type: "types.NullableDatatypeID", JSONTag: "datatype_id", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "Status", Type: "types.ContentStatus", JSONTag: "status", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "content_data_gen.go",
	},

	// ContentFields
	{
		Name:               "ContentFields",
		Singular:           "ContentField",
		Plural:             "ContentFields",
		SqlcTypeName:       "ContentFields",
		TableName:          "content_fields",
		IDType:             "types.ContentFieldID",
		IDField:            "ContentFieldID",
		NewIDFunc:          "types.NewContentFieldID()",
		UpdateSuccessField: "s.ContentFieldID",
		Fields: []Field{
			{AppName: "ContentFieldID", Type: "types.ContentFieldID", JSONTag: "content_field_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "RouteID", Type: "types.NullableRouteID", JSONTag: "route_id", InCreate: true, InUpdate: true},
			{AppName: "ContentDataID", Type: "types.NullableContentID", JSONTag: "content_data_id", InCreate: true, InUpdate: true},
			{AppName: "FieldID", Type: "types.NullableFieldID", JSONTag: "field_id", InCreate: true, InUpdate: true},
			{AppName: "FieldValue", Type: "string", JSONTag: "field_value", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "content_field_gen.go",
	},

	// AdminContentData
	{
		Name:               "AdminContentData",
		Singular:           "AdminContentData",
		Plural:             "AdminContentData",
		SqlcTypeName:       "AdminContentData",
		TableName:          "admin_content_data",
		IDType:             "types.AdminContentID",
		IDField:            "AdminContentDataID",
		NewIDFunc:          "types.NewAdminContentID()",
		HasPaginated:       true,
		UpdateSuccessField: "s.AdminContentDataID",
		Fields: []Field{
			{AppName: "AdminContentDataID", Type: "types.AdminContentID", JSONTag: "admin_content_data_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "ParentID", Type: "types.NullableAdminContentID", JSONTag: "parent_id", InCreate: true, InUpdate: true},
			{AppName: "FirstChildID", Type: "types.NullableAdminContentID", JSONTag: "first_child_id", InCreate: true, InUpdate: true},
			{AppName: "NextSiblingID", Type: "types.NullableAdminContentID", JSONTag: "next_sibling_id", InCreate: true, InUpdate: true},
			{AppName: "PrevSiblingID", Type: "types.NullableAdminContentID", JSONTag: "prev_sibling_id", InCreate: true, InUpdate: true},
			{AppName: "AdminRouteID", Type: "types.NullableAdminRouteID", JSONTag: "admin_route_id", InCreate: true, InUpdate: true},
			{AppName: "AdminDatatypeID", Type: "types.NullableAdminDatatypeID", JSONTag: "admin_datatype_id", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "Status", Type: "types.ContentStatus", JSONTag: "status", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "admin_content_data_gen.go",
	},

	// AdminContentFields
	{
		Name:               "AdminContentFields",
		Singular:           "AdminContentField",
		Plural:             "AdminContentFields",
		SqlcTypeName:       "AdminContentFields",
		TableName:          "admin_content_fields",
		IDType:             "types.AdminContentFieldID",
		IDField:            "AdminContentFieldID",
		NewIDFunc:          "types.NewAdminContentFieldID()",
		UpdateSuccessField: "s.AdminContentFieldID",
		Fields: []Field{
			{AppName: "AdminContentFieldID", Type: "types.AdminContentFieldID", JSONTag: "admin_content_field_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "AdminRouteID", Type: "types.NullableAdminRouteID", JSONTag: "admin_route_id", InCreate: true, InUpdate: true},
			{AppName: "AdminContentDataID", Type: "types.NullableAdminContentID", JSONTag: "admin_content_data_id", InCreate: true, InUpdate: true},
			{AppName: "AdminFieldID", Type: "types.NullableAdminFieldID", JSONTag: "admin_field_id", InCreate: true, InUpdate: true},
			{AppName: "AdminFieldValue", Type: "string", JSONTag: "admin_field_value", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "admin_content_field_gen.go",
	},

	// AdminDatatypes
	{
		Name:               "AdminDatatypes",
		Singular:           "AdminDatatype",
		Plural:             "AdminDatatypes",
		SqlcTypeName:       "AdminDatatypes",
		TableName:          "admin_datatypes",
		IDType:             "types.AdminDatatypeID",
		IDField:            "AdminDatatypeID",
		NewIDFunc:          "types.NewAdminDatatypeID()",
		UpdateSuccessField: "s.Label",
		Fields: []Field{
			{AppName: "AdminDatatypeID", Type: "types.AdminDatatypeID", JSONTag: "admin_datatype_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "ParentID", Type: "types.NullableAdminDatatypeID", JSONTag: "parent_id", InCreate: true, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "Type", Type: "string", JSONTag: "type", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "admin_datatype_gen.go",
	},

	// AdminFields
	{
		Name:               "AdminFields",
		Singular:           "AdminField",
		Plural:             "AdminFields",
		SqlcTypeName:       "AdminFields",
		TableName:          "admin_fields",
		IDType:             "types.AdminFieldID",
		IDField:            "AdminFieldID",
		NewIDFunc:          "types.NewAdminFieldID()",
		UpdateSuccessField: "s.Label",
		Fields: []Field{
			{AppName: "AdminFieldID", Type: "types.AdminFieldID", JSONTag: "admin_field_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "ParentID", Type: "types.NullableAdminDatatypeID", JSONTag: "parent_id", InCreate: true, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "Data", Type: "string", JSONTag: "data", InCreate: true, InUpdate: true},
			{AppName: "Validation", Type: "string", JSONTag: "validation", InCreate: true, InUpdate: true},
			{AppName: "UIConfig", SqlcName: "UiConfig", Type: "string", JSONTag: "ui_config", InCreate: true, InUpdate: true},
			{AppName: "Type", Type: "types.FieldType", JSONTag: "type", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "admin_field_gen.go",
	},

	// Datatypes (CallerSuppliedID)
	{
		Name:               "Datatypes",
		Singular:           "Datatype",
		Plural:             "Datatypes",
		SqlcTypeName:       "Datatypes",
		TableName:          "datatypes",
		IDType:             "types.DatatypeID",
		IDField:            "DatatypeID",
		NewIDFunc:          "types.NewDatatypeID()",
		CallerSuppliedID:   true,
		UpdateSuccessField: "s.Label",
		Fields: []Field{
			{AppName: "DatatypeID", Type: "types.DatatypeID", JSONTag: "datatype_id", IsPrimaryID: true, InCreate: true, InUpdate: true},
			{AppName: "ParentID", Type: "types.NullableDatatypeID", JSONTag: "parent_id", InCreate: true, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "Type", Type: "string", JSONTag: "type", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "datatype_gen.go",
	},

	// Fields (CallerSuppliedID)
	{
		Name:               "Fields",
		Singular:           "Field",
		Plural:             "Fields",
		SqlcTypeName:       "Fields",
		TableName:          "fields",
		IDType:             "types.FieldID",
		IDField:            "FieldID",
		NewIDFunc:          "types.NewFieldID()",
		CallerSuppliedID:   true,
		UpdateSuccessField: "s.Label",
		Fields: []Field{
			{AppName: "FieldID", Type: "types.FieldID", JSONTag: "field_id", IsPrimaryID: true, InCreate: true, InUpdate: true},
			{AppName: "ParentID", Type: "types.NullableDatatypeID", JSONTag: "parent_id", InCreate: true, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "Data", Type: "string", JSONTag: "data", InCreate: true, InUpdate: true},
			{AppName: "Validation", Type: "string", JSONTag: "validation", InCreate: true, InUpdate: true},
			{AppName: "UIConfig", SqlcName: "UiConfig", Type: "string", JSONTag: "ui_config", InCreate: true, InUpdate: true},
			{AppName: "Type", Type: "types.FieldType", JSONTag: "type", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "field_gen.go",
	},

	// DatatypeFields (CallerSuppliedID, no sqlc Get, special sqlc type name)
	{
		Name:                "DatatypeFields",
		Singular:            "DatatypeField",
		Plural:              "DatatypeFields",
		SqlcTypeName:        "DatatypesFields",
		TableName:           "datatypes_fields",
		IDType:              "string",
		IDField:             "ID",
		NewIDFunc:           "string(types.NewDatatypeFieldID())",
		CallerSuppliedID:    true,
		SkipAuditedCommands: true,
		SkipGet:             true,
		SqlcCreateTableName: "CreateDatatypesFieldsTable",
		UpdateSuccessField:  "s.ID",
		Fields: []Field{
			{AppName: "ID", Type: "string", JSONTag: "id", IsPrimaryID: true, InCreate: true, InUpdate: true},
			{AppName: "DatatypeID", Type: "types.DatatypeID", JSONTag: "datatype_id", InCreate: true, InUpdate: true},
			{AppName: "FieldID", Type: "types.FieldID", JSONTag: "field_id", InCreate: true, InUpdate: true},
			{AppName: "SortOrder", Type: "int64", JSONTag: "sort_order", InCreate: true, InUpdate: true},
		},
		OutputFile: "datatype_field_gen.go",
	},

	// AdminDatatypeFields (no sqlc Get, special sqlc type name)
	{
		Name:                "AdminDatatypeFields",
		Singular:            "AdminDatatypeField",
		Plural:              "AdminDatatypeFields",
		SqlcTypeName:        "AdminDatatypesFields",
		TableName:           "admin_datatypes_fields",
		IDType:              "string",
		IDField:             "ID",
		NewIDFunc:           "string(types.NewAdminDatatypeFieldID())",
		SkipAuditedCommands: true,
		SkipGet:             true,
		SqlcCreateTableName: "CreateAdminDatatypesFieldsTable",
		UpdateSuccessField:  "s.ID",
		Fields: []Field{
			{AppName: "ID", Type: "string", JSONTag: "id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "AdminDatatypeID", Type: "types.AdminDatatypeID", JSONTag: "admin_datatype_id", InCreate: true, InUpdate: true},
			{AppName: "AdminFieldID", Type: "types.AdminFieldID", JSONTag: "admin_field_id", InCreate: true, InUpdate: true},
		},
		OutputFile: "admin_datatype_field_gen.go",
	},

	// ===================================================
	// SKIP MAPPERS + AUDITED COMMANDS (per-driver diffs)
	// ===================================================

	// Roles (SystemProtected: bool vs int64 per-driver)
	{
		Name:                "Roles",
		Singular:            "Role",
		Plural:              "Roles",
		SqlcTypeName:        "Roles",
		TableName:           "roles",
		IDType:              "types.RoleID",
		IDField:             "RoleID",
		NewIDFunc:           "types.NewRoleID()",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		UpdateSuccessField:  "s.Label",
		Fields: []Field{
			{AppName: "RoleID", Type: "types.RoleID", JSONTag: "role_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "SystemProtected", Type: "bool", JSONTag: "system_protected", InCreate: true, InUpdate: true},
		},
		OutputFile: "role_gen.go",
	},

	// Permissions (SystemProtected: bool vs int64 per-driver)
	{
		Name:                "Permissions",
		Singular:            "Permission",
		Plural:              "Permissions",
		SqlcTypeName:        "Permissions",
		TableName:           "permissions",
		IDType:              "types.PermissionID",
		IDField:             "PermissionID",
		NewIDFunc:           "types.NewPermissionID()",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		UpdateSuccessField:  "s.Label",
		Fields: []Field{
			{AppName: "PermissionID", Type: "types.PermissionID", JSONTag: "permission_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "Label", Type: "string", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "SystemProtected", Type: "bool", JSONTag: "system_protected", InCreate: true, InUpdate: true},
		},
		OutputFile: "permission_gen.go",
	},

	// Tokens (Token→Tokens field remap, IssuedAt per-driver time conversion)
	{
		Name:                "Tokens",
		Singular:            "Token",
		Plural:              "Tokens",
		SqlcTypeName:        "Tokens",
		TableName:           "tokens",
		IDType:              "string",
		IDField:             "ID",
		NewIDFunc:           "string(types.NewTokenID())",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		UpdateSuccessField:  "s.ID",
		Fields: []Field{
			{AppName: "ID", Type: "string", JSONTag: "id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "UserID", Type: "types.NullableUserID", JSONTag: "user_id", InCreate: true, InUpdate: false},
			{AppName: "TokenType", Type: "string", JSONTag: "token_type", InCreate: true, InUpdate: false},
			{AppName: "Token", Type: "string", JSONTag: "token", InCreate: true, InUpdate: true},
			{AppName: "IssuedAt", Type: "string", JSONTag: "issued_at", InCreate: true, InUpdate: true},
			{AppName: "ExpiresAt", Type: "types.Timestamp", JSONTag: "expires_at", InCreate: true, InUpdate: true},
			{AppName: "Revoked", Type: "bool", JSONTag: "revoked", InCreate: true, InUpdate: true},
		},
		OutputFile: "token_gen.go",
	},

	// Sessions (LastAccess per-driver time conversion)
	{
		Name:                "Sessions",
		Singular:            "Session",
		Plural:              "Sessions",
		SqlcTypeName:        "Sessions",
		TableName:           "sessions",
		IDType:              "types.SessionID",
		IDField:             "SessionID",
		NewIDFunc:           "types.NewSessionID()",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		UpdateSuccessField:  "s.SessionID",
		Fields: []Field{
			{AppName: "SessionID", Type: "types.SessionID", JSONTag: "session_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "UserID", Type: "types.NullableUserID", JSONTag: "user_id", InCreate: true, InUpdate: true},
			{AppName: "CreatedAt", Type: "types.Timestamp", JSONTag: "created_at", InCreate: true, InUpdate: true},
			{AppName: "ExpiresAt", Type: "types.Timestamp", JSONTag: "expires_at", InCreate: true, InUpdate: true},
			{AppName: "LastAccess", Type: "sql.NullString", JSONTag: "last_access", InCreate: true, InUpdate: true},
			{AppName: "IpAddress", Type: "sql.NullString", JSONTag: "ip_address", InCreate: true, InUpdate: true},
			{AppName: "UserAgent", Type: "sql.NullString", JSONTag: "user_agent", InCreate: true, InUpdate: true},
			{AppName: "SessionData", Type: "sql.NullString", JSONTag: "session_data", InCreate: true, InUpdate: true},
		},
		OutputFile: "session_gen.go",
	},

	// MediaDimensions (Width/Height int64 vs int32 per-driver)
	{
		Name:                "MediaDimensions",
		Singular:            "MediaDimension",
		Plural:              "MediaDimensions",
		SqlcTypeName:        "MediaDimensions",
		TableName:           "media_dimensions",
		IDType:              "string",
		IDField:             "MdID",
		NewIDFunc:           "string(types.NewMediaDimensionID())",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		UpdateSuccessField:  "s.MdID",
		Fields: []Field{
			{AppName: "MdID", Type: "string", JSONTag: "md_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "Label", Type: "sql.NullString", JSONTag: "label", InCreate: true, InUpdate: true},
			{AppName: "Width", Type: "sql.NullInt64", JSONTag: "width", InCreate: true, InUpdate: true},
			{AppName: "Height", Type: "sql.NullInt64", JSONTag: "height", InCreate: true, InUpdate: true},
			{AppName: "AspectRatio", Type: "sql.NullString", JSONTag: "aspect_ratio", InCreate: true, InUpdate: true},
		},
		OutputFile: "media_dimension_gen.go",
	},

	// UserOauth (OAuthID casing per-driver, TokenExpiresAt per-driver)
	{
		Name:                "UserOauth",
		Singular:            "UserOauth",
		Plural:              "UserOauths",
		SqlcTypeName:        "UserOauth",
		TableName:           "user_oauth",
		IDType:              "types.UserOauthID",
		IDField:             "UserOauthID",
		NewIDFunc:           "types.NewUserOauthID()",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		SkipGet:             true,
		UpdateSuccessField:  "s.UserOauthID",
		Fields: []Field{
			{AppName: "UserOauthID", Type: "types.UserOauthID", JSONTag: "user_oauth_id", IsPrimaryID: true, InCreate: false, InUpdate: true},
			{AppName: "UserID", Type: "types.NullableUserID", JSONTag: "user_id", InCreate: true, InUpdate: false},
			{AppName: "OauthProvider", Type: "string", JSONTag: "oauth_provider", InCreate: true, InUpdate: false},
			{AppName: "OauthProviderUserID", Type: "string", JSONTag: "oauth_provider_user_id", InCreate: true, InUpdate: false},
			{AppName: "AccessToken", Type: "string", JSONTag: "access_token", InCreate: true, InUpdate: true},
			{AppName: "RefreshToken", Type: "string", JSONTag: "refresh_token", InCreate: true, InUpdate: true},
			{AppName: "TokenExpiresAt", Type: "string", JSONTag: "token_expires_at", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: false},
		},
		OutputFile: "user_oauth_gen.go",
	},

	// Routes (Slug_2 update WHERE, Status int conversion per-driver)
	{
		Name:                "Routes",
		Singular:            "Route",
		Plural:              "Routes",
		SqlcTypeName:        "Routes",
		TableName:           "routes",
		IDType:              "types.RouteID",
		IDField:             "RouteID",
		NewIDFunc:           "types.NewRouteID()",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		UpdateSuccessField:  "s.Slug",
		Fields: []Field{
			{AppName: "RouteID", Type: "types.RouteID", JSONTag: "route_id", IsPrimaryID: true, InCreate: false, InUpdate: false},
			{AppName: "Slug", Type: "types.Slug", JSONTag: "slug", InCreate: true, InUpdate: true},
			{AppName: "Title", Type: "string", JSONTag: "title", InCreate: true, InUpdate: true},
			{AppName: "Status", Type: "int64", JSONTag: "status", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "route_gen.go",
	},

	// AdminRoutes (Slug_2 update WHERE, Status int conversion, no sqlc Get)
	{
		Name:                "AdminRoutes",
		Singular:            "AdminRoute",
		Plural:              "AdminRoutes",
		SqlcTypeName:        "AdminRoutes",
		TableName:           "admin_routes",
		IDType:              "types.AdminRouteID",
		IDField:             "AdminRouteID",
		NewIDFunc:           "types.NewAdminRouteID()",
		SkipMappers:         true,
		SkipAuditedCommands: true,
		SkipGet:             true,
		SqlcCountName:       "CountAdminRoute",
		UpdateSuccessField:  "s.Slug",
		Fields: []Field{
			{AppName: "AdminRouteID", Type: "types.AdminRouteID", JSONTag: "admin_route_id", IsPrimaryID: true, InCreate: false, InUpdate: false},
			{AppName: "Slug", Type: "types.Slug", JSONTag: "slug", InCreate: true, InUpdate: true},
			{AppName: "Title", Type: "string", JSONTag: "title", InCreate: true, InUpdate: true},
			{AppName: "Status", Type: "int64", JSONTag: "status", InCreate: true, InUpdate: true},
			{AppName: "AuthorID", Type: "types.NullableUserID", JSONTag: "author_id", InCreate: true, InUpdate: true},
			{AppName: "DateCreated", Type: "types.Timestamp", JSONTag: "date_created", InCreate: true, InUpdate: true},
			{AppName: "DateModified", Type: "types.Timestamp", JSONTag: "date_modified", InCreate: true, InUpdate: true},
		},
		OutputFile: "admin_route_gen.go",
	},
}
