// Code generated by tools/dbgen; DO NOT EDIT.
package db

import (
	"fmt"

	mdbm "github.com/hegner123/modulacms/internal/db-mysql"
	mdbp "github.com/hegner123/modulacms/internal/db-psql"
	mdb "github.com/hegner123/modulacms/internal/db-sqlite"
	"github.com/hegner123/modulacms/internal/db/types"
)

///////////////////////////////
// STRUCTS
//////////////////////////////

// AdminRoutes represents a adminRoute record in the database.
type AdminRoutes struct {
	AdminRouteID types.AdminRouteID   `json:"admin_route_id"`
	Slug         types.Slug           `json:"slug"`
	Title        string               `json:"title"`
	Status       int64                `json:"status"`
	AuthorID     types.NullableUserID `json:"author_id"`
	DateCreated  types.Timestamp      `json:"date_created"`
	DateModified types.Timestamp      `json:"date_modified"`
}

// CreateAdminRouteParams contains parameters for creating a new adminRoute.
type CreateAdminRouteParams struct {
	Slug         types.Slug           `json:"slug"`
	Title        string               `json:"title"`
	Status       int64                `json:"status"`
	AuthorID     types.NullableUserID `json:"author_id"`
	DateCreated  types.Timestamp      `json:"date_created"`
	DateModified types.Timestamp      `json:"date_modified"`
}

// UpdateAdminRouteParams contains parameters for updating an existing adminRoute.
type UpdateAdminRouteParams struct {
	Slug         types.Slug           `json:"slug"`
	Title        string               `json:"title"`
	Status       int64                `json:"status"`
	AuthorID     types.NullableUserID `json:"author_id"`
	DateCreated  types.Timestamp      `json:"date_created"`
	DateModified types.Timestamp      `json:"date_modified"`
	Slug_2       types.Slug           `json:"slug_2"`
}

// MapStringAdminRoute converts AdminRoutes to StringAdminRoutes for TUI display.
func MapStringAdminRoute(a AdminRoutes) StringAdminRoutes {
	return StringAdminRoutes{
		AdminRouteID: a.AdminRouteID.String(),
		Slug:         string(a.Slug),
		Title:        a.Title,
		Status:       fmt.Sprintf("%d", a.Status),
		AuthorID:     a.AuthorID.String(),
		DateCreated:  a.DateCreated.String(),
		DateModified: a.DateModified.String(),
		History:      "",
	}
}

///////////////////////////////
// SQLITE
//////////////////////////////

// MAPS

// MapAdminRoute converts a sqlc-generated SQLite adminRoute to the wrapper type.
func (d Database) MapAdminRoute(a mdb.AdminRoutes) AdminRoutes {
	return AdminRoutes{
		AdminRouteID: a.AdminRouteID,
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       a.Status,
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
	}
}

// MapCreateAdminRouteParams converts wrapper params to sqlc-generated SQLite params.
func (d Database) MapCreateAdminRouteParams(a CreateAdminRouteParams) mdb.CreateAdminRouteParams {
	return mdb.CreateAdminRouteParams{
		AdminRouteID: types.NewAdminRouteID(),
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       a.Status,
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
	}
}

// MapUpdateAdminRouteParams converts wrapper params to sqlc-generated SQLite params.
func (d Database) MapUpdateAdminRouteParams(a UpdateAdminRouteParams) mdb.UpdateAdminRouteParams {
	return mdb.UpdateAdminRouteParams{
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       a.Status,
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
		Slug_2:       a.Slug_2,
	}
}

// QUERIES

// CountAdminRoutes returns the total number of adminRoutes in the database.
func (d Database) CountAdminRoutes() (*int64, error) {
	queries := mdb.New(d.Connection)
	c, err := queries.CountAdminRoute(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateAdminRouteTable creates the admin_routes table in the database.
func (d Database) CreateAdminRouteTable() error {
	queries := mdb.New(d.Connection)
	err := queries.CreateAdminRouteTable(d.Context)
	return err
}

// ListAdminRoutes retrieves all adminRoutes in the database.
func (d Database) ListAdminRoutes() (*[]AdminRoutes, error) {
	queries := mdb.New(d.Connection)
	rows, err := queries.ListAdminRoute(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get AdminRoutes: %v\n", err)
	}
	res := []AdminRoutes{}
	for _, v := range rows {
		m := d.MapAdminRoute(v)
		res = append(res, m)
	}
	return &res, nil
}

///////////////////////////////
// MYSQL
//////////////////////////////

// MAPS

// MapAdminRoute converts a sqlc-generated MySQL adminRoute to the wrapper type.
func (d MysqlDatabase) MapAdminRoute(a mdbm.AdminRoutes) AdminRoutes {
	return AdminRoutes{
		AdminRouteID: a.AdminRouteID,
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       int64(a.Status),
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
	}
}

// MapCreateAdminRouteParams converts wrapper params to sqlc-generated MySQL params.
func (d MysqlDatabase) MapCreateAdminRouteParams(a CreateAdminRouteParams) mdbm.CreateAdminRouteParams {
	return mdbm.CreateAdminRouteParams{
		AdminRouteID: types.NewAdminRouteID(),
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       int32(a.Status),
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
	}
}

// MapUpdateAdminRouteParams converts wrapper params to sqlc-generated MySQL params.
func (d MysqlDatabase) MapUpdateAdminRouteParams(a UpdateAdminRouteParams) mdbm.UpdateAdminRouteParams {
	return mdbm.UpdateAdminRouteParams{
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       int32(a.Status),
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
		Slug_2:       a.Slug_2,
	}
}

// QUERIES

// CountAdminRoutes returns the total number of adminRoutes in the database.
func (d MysqlDatabase) CountAdminRoutes() (*int64, error) {
	queries := mdbm.New(d.Connection)
	c, err := queries.CountAdminRoute(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateAdminRouteTable creates the admin_routes table in the database.
func (d MysqlDatabase) CreateAdminRouteTable() error {
	queries := mdbm.New(d.Connection)
	err := queries.CreateAdminRouteTable(d.Context)
	return err
}

// ListAdminRoutes retrieves all adminRoutes in the database.
func (d MysqlDatabase) ListAdminRoutes() (*[]AdminRoutes, error) {
	queries := mdbm.New(d.Connection)
	rows, err := queries.ListAdminRoute(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get AdminRoutes: %v\n", err)
	}
	res := []AdminRoutes{}
	for _, v := range rows {
		m := d.MapAdminRoute(v)
		res = append(res, m)
	}
	return &res, nil
}

///////////////////////////////
// POSTGRES
//////////////////////////////

// MAPS

// MapAdminRoute converts a sqlc-generated PostgreSQL adminRoute to the wrapper type.
func (d PsqlDatabase) MapAdminRoute(a mdbp.AdminRoutes) AdminRoutes {
	return AdminRoutes{
		AdminRouteID: a.AdminRouteID,
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       int64(a.Status),
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
	}
}

// MapCreateAdminRouteParams converts wrapper params to sqlc-generated PostgreSQL params.
func (d PsqlDatabase) MapCreateAdminRouteParams(a CreateAdminRouteParams) mdbp.CreateAdminRouteParams {
	return mdbp.CreateAdminRouteParams{
		AdminRouteID: types.NewAdminRouteID(),
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       int32(a.Status),
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
	}
}

// MapUpdateAdminRouteParams converts wrapper params to sqlc-generated PostgreSQL params.
func (d PsqlDatabase) MapUpdateAdminRouteParams(a UpdateAdminRouteParams) mdbp.UpdateAdminRouteParams {
	return mdbp.UpdateAdminRouteParams{
		Slug:         a.Slug,
		Title:        a.Title,
		Status:       int32(a.Status),
		AuthorID:     a.AuthorID,
		DateCreated:  a.DateCreated,
		DateModified: a.DateModified,
		Slug_2:       a.Slug_2,
	}
}

// QUERIES

// CountAdminRoutes returns the total number of adminRoutes in the database.
func (d PsqlDatabase) CountAdminRoutes() (*int64, error) {
	queries := mdbp.New(d.Connection)
	c, err := queries.CountAdminRoute(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateAdminRouteTable creates the admin_routes table in the database.
func (d PsqlDatabase) CreateAdminRouteTable() error {
	queries := mdbp.New(d.Connection)
	err := queries.CreateAdminRouteTable(d.Context)
	return err
}

// ListAdminRoutes retrieves all adminRoutes in the database.
func (d PsqlDatabase) ListAdminRoutes() (*[]AdminRoutes, error) {
	queries := mdbp.New(d.Connection)
	rows, err := queries.ListAdminRoute(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get AdminRoutes: %v\n", err)
	}
	res := []AdminRoutes{}
	for _, v := range rows {
		m := d.MapAdminRoute(v)
		res = append(res, m)
	}
	return &res, nil
}
