// Code generated by tools/dbgen; DO NOT EDIT.
package db

import (
	"context"
	"database/sql"
	"fmt"

	mdbm "github.com/hegner123/modulacms/internal/db-mysql"
	mdbp "github.com/hegner123/modulacms/internal/db-psql"
	mdb "github.com/hegner123/modulacms/internal/db-sqlite"
	"github.com/hegner123/modulacms/internal/db/audited"
	"github.com/hegner123/modulacms/internal/db/types"
)

///////////////////////////////
// STRUCTS
//////////////////////////////

// FieldTypes represents a fieldType record in the database.
type FieldTypes struct {
	FieldTypeID types.FieldTypeID `json:"field_type_id"`
	Type        string            `json:"type"`
	Label       string            `json:"label"`
}

// CreateFieldTypeParams contains parameters for creating a new fieldType.
type CreateFieldTypeParams struct {
	Type  string `json:"type"`
	Label string `json:"label"`
}

// UpdateFieldTypeParams contains parameters for updating an existing fieldType.
type UpdateFieldTypeParams struct {
	Type        string            `json:"type"`
	Label       string            `json:"label"`
	FieldTypeID types.FieldTypeID `json:"field_type_id"`
}

// MapStringFieldType converts FieldTypes to StringFieldTypes for TUI display.
func MapStringFieldType(a FieldTypes) StringFieldTypes {
	return StringFieldTypes{
		FieldTypeID: a.FieldTypeID.String(),
		Type:        a.Type,
		Label:       a.Label,
	}
}

///////////////////////////////
// SQLITE
//////////////////////////////

// MAPS

// MapFieldType converts a sqlc-generated SQLite fieldType to the wrapper type.
func (d Database) MapFieldType(a mdb.FieldTypes) FieldTypes {
	return FieldTypes{
		FieldTypeID: a.FieldTypeID,
		Type:        a.Type,
		Label:       a.Label,
	}
}

// MapCreateFieldTypeParams converts wrapper params to sqlc-generated SQLite params.
func (d Database) MapCreateFieldTypeParams(a CreateFieldTypeParams) mdb.CreateFieldTypesParams {
	return mdb.CreateFieldTypesParams{
		FieldTypeID: types.NewFieldTypeID(),
		Type:        a.Type,
		Label:       a.Label,
	}
}

// MapUpdateFieldTypeParams converts wrapper params to sqlc-generated SQLite params.
func (d Database) MapUpdateFieldTypeParams(a UpdateFieldTypeParams) mdb.UpdateFieldTypesParams {
	return mdb.UpdateFieldTypesParams{
		Type:        a.Type,
		Label:       a.Label,
		FieldTypeID: a.FieldTypeID,
	}
}

// QUERIES

// CountFieldTypes returns the total number of fieldTypes in the database.
func (d Database) CountFieldTypes() (*int64, error) {
	queries := mdb.New(d.Connection)
	c, err := queries.CountFieldTypes(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateFieldTypeTable creates the field_types table in the database.
func (d Database) CreateFieldTypeTable() error {
	queries := mdb.New(d.Connection)
	err := queries.CreateFieldTypesTable(d.Context)
	return err
}

// CreateFieldType inserts a new fieldType and records an audit event.
func (d Database) CreateFieldType(ctx context.Context, ac audited.AuditContext, s CreateFieldTypeParams) (*FieldTypes, error) {
	cmd := d.NewFieldTypeCmd(ctx, ac, s)
	result, err := audited.Create(cmd)
	if err != nil {
		return nil, fmt.Errorf("failed to create fieldType: %w", err)
	}
	r := d.MapFieldType(result)
	return &r, nil
}

// DeleteFieldType removes a fieldType and records an audit event.
func (d Database) DeleteFieldType(ctx context.Context, ac audited.AuditContext, id types.FieldTypeID) error {
	cmd := d.DeleteFieldTypeCmd(ctx, ac, id)
	return audited.Delete(cmd)
}

// GetFieldType retrieves a fieldType by ID.
func (d Database) GetFieldType(id types.FieldTypeID) (*FieldTypes, error) {
	queries := mdb.New(d.Connection)
	row, err := queries.GetFieldTypes(d.Context, mdb.GetFieldTypesParams{FieldTypeID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapFieldType(row)
	return &res, nil
}

// ListFieldTypes retrieves all fieldTypes in the database.
func (d Database) ListFieldTypes() (*[]FieldTypes, error) {
	queries := mdb.New(d.Connection)
	rows, err := queries.ListFieldTypes(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get FieldTypes: %v\n", err)
	}
	res := []FieldTypes{}
	for _, v := range rows {
		m := d.MapFieldType(v)
		res = append(res, m)
	}
	return &res, nil
}

// UpdateFieldType modifies an existing fieldType and records an audit event.
func (d Database) UpdateFieldType(ctx context.Context, ac audited.AuditContext, s UpdateFieldTypeParams) (*string, error) {
	cmd := d.UpdateFieldTypeCmd(ctx, ac, s)
	if err := audited.Update(cmd); err != nil {
		return nil, fmt.Errorf("failed to update fieldType: %w", err)
	}
	msg := fmt.Sprintf("Successfully updated %v\n", s.Type)
	return &msg, nil
}

// GetFieldTypeByType retrieves a fieldType by fieldType.
func (d Database) GetFieldTypeByType(fieldType string) (*FieldTypes, error) {
	queries := mdb.New(d.Connection)
	row, err := queries.GetFieldTypesByType(d.Context, mdb.GetFieldTypesByTypeParams{Type: fieldType})
	if err != nil {
		return nil, err
	}
	res := d.MapFieldType(row)
	return &res, nil
}

///////////////////////////////
// MYSQL
//////////////////////////////

// MAPS

// MapFieldType converts a sqlc-generated MySQL fieldType to the wrapper type.
func (d MysqlDatabase) MapFieldType(a mdbm.FieldTypes) FieldTypes {
	return FieldTypes{
		FieldTypeID: a.FieldTypeID,
		Type:        a.Type,
		Label:       a.Label,
	}
}

// MapCreateFieldTypeParams converts wrapper params to sqlc-generated MySQL params.
func (d MysqlDatabase) MapCreateFieldTypeParams(a CreateFieldTypeParams) mdbm.CreateFieldTypesParams {
	return mdbm.CreateFieldTypesParams{
		FieldTypeID: types.NewFieldTypeID(),
		Type:        a.Type,
		Label:       a.Label,
	}
}

// MapUpdateFieldTypeParams converts wrapper params to sqlc-generated MySQL params.
func (d MysqlDatabase) MapUpdateFieldTypeParams(a UpdateFieldTypeParams) mdbm.UpdateFieldTypesParams {
	return mdbm.UpdateFieldTypesParams{
		Type:        a.Type,
		Label:       a.Label,
		FieldTypeID: a.FieldTypeID,
	}
}

// QUERIES

// CountFieldTypes returns the total number of fieldTypes in the database.
func (d MysqlDatabase) CountFieldTypes() (*int64, error) {
	queries := mdbm.New(d.Connection)
	c, err := queries.CountFieldTypes(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateFieldTypeTable creates the field_types table in the database.
func (d MysqlDatabase) CreateFieldTypeTable() error {
	queries := mdbm.New(d.Connection)
	err := queries.CreateFieldTypesTable(d.Context)
	return err
}

// CreateFieldType inserts a new fieldType and records an audit event.
func (d MysqlDatabase) CreateFieldType(ctx context.Context, ac audited.AuditContext, s CreateFieldTypeParams) (*FieldTypes, error) {
	cmd := d.NewFieldTypeCmd(ctx, ac, s)
	result, err := audited.Create(cmd)
	if err != nil {
		return nil, fmt.Errorf("failed to create fieldType: %w", err)
	}
	r := d.MapFieldType(result)
	return &r, nil
}

// DeleteFieldType removes a fieldType and records an audit event.
func (d MysqlDatabase) DeleteFieldType(ctx context.Context, ac audited.AuditContext, id types.FieldTypeID) error {
	cmd := d.DeleteFieldTypeCmd(ctx, ac, id)
	return audited.Delete(cmd)
}

// GetFieldType retrieves a fieldType by ID.
func (d MysqlDatabase) GetFieldType(id types.FieldTypeID) (*FieldTypes, error) {
	queries := mdbm.New(d.Connection)
	row, err := queries.GetFieldTypes(d.Context, mdbm.GetFieldTypesParams{FieldTypeID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapFieldType(row)
	return &res, nil
}

// ListFieldTypes retrieves all fieldTypes in the database.
func (d MysqlDatabase) ListFieldTypes() (*[]FieldTypes, error) {
	queries := mdbm.New(d.Connection)
	rows, err := queries.ListFieldTypes(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get FieldTypes: %v\n", err)
	}
	res := []FieldTypes{}
	for _, v := range rows {
		m := d.MapFieldType(v)
		res = append(res, m)
	}
	return &res, nil
}

// UpdateFieldType modifies an existing fieldType and records an audit event.
func (d MysqlDatabase) UpdateFieldType(ctx context.Context, ac audited.AuditContext, s UpdateFieldTypeParams) (*string, error) {
	cmd := d.UpdateFieldTypeCmd(ctx, ac, s)
	if err := audited.Update(cmd); err != nil {
		return nil, fmt.Errorf("failed to update fieldType: %w", err)
	}
	msg := fmt.Sprintf("Successfully updated %v\n", s.Type)
	return &msg, nil
}

// GetFieldTypeByType retrieves a fieldType by fieldType.
func (d MysqlDatabase) GetFieldTypeByType(fieldType string) (*FieldTypes, error) {
	queries := mdbm.New(d.Connection)
	row, err := queries.GetFieldTypesByType(d.Context, mdbm.GetFieldTypesByTypeParams{Type: fieldType})
	if err != nil {
		return nil, err
	}
	res := d.MapFieldType(row)
	return &res, nil
}

///////////////////////////////
// POSTGRES
//////////////////////////////

// MAPS

// MapFieldType converts a sqlc-generated PostgreSQL fieldType to the wrapper type.
func (d PsqlDatabase) MapFieldType(a mdbp.FieldTypes) FieldTypes {
	return FieldTypes{
		FieldTypeID: a.FieldTypeID,
		Type:        a.Type,
		Label:       a.Label,
	}
}

// MapCreateFieldTypeParams converts wrapper params to sqlc-generated PostgreSQL params.
func (d PsqlDatabase) MapCreateFieldTypeParams(a CreateFieldTypeParams) mdbp.CreateFieldTypesParams {
	return mdbp.CreateFieldTypesParams{
		FieldTypeID: types.NewFieldTypeID(),
		Type:        a.Type,
		Label:       a.Label,
	}
}

// MapUpdateFieldTypeParams converts wrapper params to sqlc-generated PostgreSQL params.
func (d PsqlDatabase) MapUpdateFieldTypeParams(a UpdateFieldTypeParams) mdbp.UpdateFieldTypesParams {
	return mdbp.UpdateFieldTypesParams{
		Type:        a.Type,
		Label:       a.Label,
		FieldTypeID: a.FieldTypeID,
	}
}

// QUERIES

// CountFieldTypes returns the total number of fieldTypes in the database.
func (d PsqlDatabase) CountFieldTypes() (*int64, error) {
	queries := mdbp.New(d.Connection)
	c, err := queries.CountFieldTypes(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateFieldTypeTable creates the field_types table in the database.
func (d PsqlDatabase) CreateFieldTypeTable() error {
	queries := mdbp.New(d.Connection)
	err := queries.CreateFieldTypesTable(d.Context)
	return err
}

// CreateFieldType inserts a new fieldType and records an audit event.
func (d PsqlDatabase) CreateFieldType(ctx context.Context, ac audited.AuditContext, s CreateFieldTypeParams) (*FieldTypes, error) {
	cmd := d.NewFieldTypeCmd(ctx, ac, s)
	result, err := audited.Create(cmd)
	if err != nil {
		return nil, fmt.Errorf("failed to create fieldType: %w", err)
	}
	r := d.MapFieldType(result)
	return &r, nil
}

// DeleteFieldType removes a fieldType and records an audit event.
func (d PsqlDatabase) DeleteFieldType(ctx context.Context, ac audited.AuditContext, id types.FieldTypeID) error {
	cmd := d.DeleteFieldTypeCmd(ctx, ac, id)
	return audited.Delete(cmd)
}

// GetFieldType retrieves a fieldType by ID.
func (d PsqlDatabase) GetFieldType(id types.FieldTypeID) (*FieldTypes, error) {
	queries := mdbp.New(d.Connection)
	row, err := queries.GetFieldTypes(d.Context, mdbp.GetFieldTypesParams{FieldTypeID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapFieldType(row)
	return &res, nil
}

// ListFieldTypes retrieves all fieldTypes in the database.
func (d PsqlDatabase) ListFieldTypes() (*[]FieldTypes, error) {
	queries := mdbp.New(d.Connection)
	rows, err := queries.ListFieldTypes(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get FieldTypes: %v\n", err)
	}
	res := []FieldTypes{}
	for _, v := range rows {
		m := d.MapFieldType(v)
		res = append(res, m)
	}
	return &res, nil
}

// UpdateFieldType modifies an existing fieldType and records an audit event.
func (d PsqlDatabase) UpdateFieldType(ctx context.Context, ac audited.AuditContext, s UpdateFieldTypeParams) (*string, error) {
	cmd := d.UpdateFieldTypeCmd(ctx, ac, s)
	if err := audited.Update(cmd); err != nil {
		return nil, fmt.Errorf("failed to update fieldType: %w", err)
	}
	msg := fmt.Sprintf("Successfully updated %v\n", s.Type)
	return &msg, nil
}

// GetFieldTypeByType retrieves a fieldType by fieldType.
func (d PsqlDatabase) GetFieldTypeByType(fieldType string) (*FieldTypes, error) {
	queries := mdbp.New(d.Connection)
	row, err := queries.GetFieldTypesByType(d.Context, mdbp.GetFieldTypesByTypeParams{Type: fieldType})
	if err != nil {
		return nil, err
	}
	res := d.MapFieldType(row)
	return &res, nil
}

// ========== AUDITED COMMAND TYPES ==========

// ----- SQLite CREATE -----

// NewFieldTypeCmd is an audited command for creating fieldTypes.
type NewFieldTypeCmd struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	params   CreateFieldTypeParams
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c NewFieldTypeCmd) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c NewFieldTypeCmd) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c NewFieldTypeCmd) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c NewFieldTypeCmd) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c NewFieldTypeCmd) TableName() string { return "field_types" }

// Params returns the parameters for this command.
func (c NewFieldTypeCmd) Params() any { return c.params }

// GetID extracts the ID from a fieldType record.
func (c NewFieldTypeCmd) GetID(u mdb.FieldTypes) string { return string(u.FieldTypeID) }

// Execute creates the fieldType in the database.
func (c NewFieldTypeCmd) Execute(ctx context.Context, tx audited.DBTX) (mdb.FieldTypes, error) {
	queries := mdb.New(tx)
	return queries.CreateFieldTypes(ctx, mdb.CreateFieldTypesParams{
		FieldTypeID: types.NewFieldTypeID(),
		Type:        c.params.Type,
		Label:       c.params.Label,
	})
}

// NewFieldTypeCmd creates a command for inserting a fieldType.
func (d Database) NewFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, params CreateFieldTypeParams) NewFieldTypeCmd {
	return NewFieldTypeCmd{ctx: ctx, auditCtx: auditCtx, params: params, conn: d.Connection, recorder: SQLiteRecorder}
}

// ----- SQLite UPDATE -----

// UpdateFieldTypeCmd is an audited command for updating fieldTypes.
type UpdateFieldTypeCmd struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	params   UpdateFieldTypeParams
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c UpdateFieldTypeCmd) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c UpdateFieldTypeCmd) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c UpdateFieldTypeCmd) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c UpdateFieldTypeCmd) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c UpdateFieldTypeCmd) TableName() string { return "field_types" }

// Params returns the parameters for this command.
func (c UpdateFieldTypeCmd) Params() any { return c.params }

// GetID returns the fieldType ID for this command.
func (c UpdateFieldTypeCmd) GetID() string { return string(c.params.FieldTypeID) }

// GetBefore retrieves the fieldType before the update.
func (c UpdateFieldTypeCmd) GetBefore(ctx context.Context, tx audited.DBTX) (mdb.FieldTypes, error) {
	queries := mdb.New(tx)
	return queries.GetFieldTypes(ctx, mdb.GetFieldTypesParams{FieldTypeID: c.params.FieldTypeID})
}

// Execute updates the fieldType in the database.
func (c UpdateFieldTypeCmd) Execute(ctx context.Context, tx audited.DBTX) error {
	queries := mdb.New(tx)
	return queries.UpdateFieldTypes(ctx, mdb.UpdateFieldTypesParams{
		Type:        c.params.Type,
		Label:       c.params.Label,
		FieldTypeID: c.params.FieldTypeID,
	})
}

// UpdateFieldTypeCmd creates a command for updating a fieldType.
func (d Database) UpdateFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, params UpdateFieldTypeParams) UpdateFieldTypeCmd {
	return UpdateFieldTypeCmd{ctx: ctx, auditCtx: auditCtx, params: params, conn: d.Connection, recorder: SQLiteRecorder}
}

// ----- SQLite DELETE -----

// DeleteFieldTypeCmd is an audited command for deleting fieldTypes.
type DeleteFieldTypeCmd struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	id       types.FieldTypeID
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c DeleteFieldTypeCmd) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c DeleteFieldTypeCmd) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c DeleteFieldTypeCmd) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c DeleteFieldTypeCmd) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c DeleteFieldTypeCmd) TableName() string { return "field_types" }

// GetID returns the fieldType ID for this command.
func (c DeleteFieldTypeCmd) GetID() string { return string(c.id) }

// GetBefore retrieves the fieldType before the delete.
func (c DeleteFieldTypeCmd) GetBefore(ctx context.Context, tx audited.DBTX) (mdb.FieldTypes, error) {
	queries := mdb.New(tx)
	return queries.GetFieldTypes(ctx, mdb.GetFieldTypesParams{FieldTypeID: c.id})
}

// Execute deletes the fieldType from the database.
func (c DeleteFieldTypeCmd) Execute(ctx context.Context, tx audited.DBTX) error {
	queries := mdb.New(tx)
	return queries.DeleteFieldTypes(ctx, mdb.DeleteFieldTypesParams{FieldTypeID: c.id})
}

// DeleteFieldTypeCmd creates a command for deleting a fieldType.
func (d Database) DeleteFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, id types.FieldTypeID) DeleteFieldTypeCmd {
	return DeleteFieldTypeCmd{ctx: ctx, auditCtx: auditCtx, id: id, conn: d.Connection, recorder: SQLiteRecorder}
}

// ----- MySQL CREATE -----

// NewFieldTypeCmdMysql is an audited command for creating fieldTypes in MySQL.
type NewFieldTypeCmdMysql struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	params   CreateFieldTypeParams
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c NewFieldTypeCmdMysql) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c NewFieldTypeCmdMysql) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c NewFieldTypeCmdMysql) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c NewFieldTypeCmdMysql) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c NewFieldTypeCmdMysql) TableName() string { return "field_types" }

// Params returns the parameters for this command.
func (c NewFieldTypeCmdMysql) Params() any { return c.params }

// GetID extracts the ID from a fieldType record.
func (c NewFieldTypeCmdMysql) GetID(u mdbm.FieldTypes) string { return string(u.FieldTypeID) }

// Execute creates the fieldType in the database.
func (c NewFieldTypeCmdMysql) Execute(ctx context.Context, tx audited.DBTX) (mdbm.FieldTypes, error) {
	queries := mdbm.New(tx)
	params := mdbm.CreateFieldTypesParams{
		FieldTypeID: types.NewFieldTypeID(),
		Type:        c.params.Type,
		Label:       c.params.Label,
	}
	if err := queries.CreateFieldTypes(ctx, params); err != nil {
		return mdbm.FieldTypes{}, err
	}
	return queries.GetFieldTypes(ctx, mdbm.GetFieldTypesParams{FieldTypeID: params.FieldTypeID})
}

// NewFieldTypeCmd creates a command for inserting a fieldType.
func (d MysqlDatabase) NewFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, params CreateFieldTypeParams) NewFieldTypeCmdMysql {
	return NewFieldTypeCmdMysql{ctx: ctx, auditCtx: auditCtx, params: params, conn: d.Connection, recorder: MysqlRecorder}
}

// ----- MySQL UPDATE -----

// UpdateFieldTypeCmdMysql is an audited command for updating fieldTypes in MySQL.
type UpdateFieldTypeCmdMysql struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	params   UpdateFieldTypeParams
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c UpdateFieldTypeCmdMysql) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c UpdateFieldTypeCmdMysql) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c UpdateFieldTypeCmdMysql) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c UpdateFieldTypeCmdMysql) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c UpdateFieldTypeCmdMysql) TableName() string { return "field_types" }

// Params returns the parameters for this command.
func (c UpdateFieldTypeCmdMysql) Params() any { return c.params }

// GetID returns the fieldType ID for this command.
func (c UpdateFieldTypeCmdMysql) GetID() string { return string(c.params.FieldTypeID) }

// GetBefore retrieves the fieldType before the update.
func (c UpdateFieldTypeCmdMysql) GetBefore(ctx context.Context, tx audited.DBTX) (mdbm.FieldTypes, error) {
	queries := mdbm.New(tx)
	return queries.GetFieldTypes(ctx, mdbm.GetFieldTypesParams{FieldTypeID: c.params.FieldTypeID})
}

// Execute updates the fieldType in the database.
func (c UpdateFieldTypeCmdMysql) Execute(ctx context.Context, tx audited.DBTX) error {
	queries := mdbm.New(tx)
	return queries.UpdateFieldTypes(ctx, mdbm.UpdateFieldTypesParams{
		Type:        c.params.Type,
		Label:       c.params.Label,
		FieldTypeID: c.params.FieldTypeID,
	})
}

// UpdateFieldTypeCmd creates a command for updating a fieldType.
func (d MysqlDatabase) UpdateFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, params UpdateFieldTypeParams) UpdateFieldTypeCmdMysql {
	return UpdateFieldTypeCmdMysql{ctx: ctx, auditCtx: auditCtx, params: params, conn: d.Connection, recorder: MysqlRecorder}
}

// ----- MySQL DELETE -----

// DeleteFieldTypeCmdMysql is an audited command for deleting fieldTypes in MySQL.
type DeleteFieldTypeCmdMysql struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	id       types.FieldTypeID
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c DeleteFieldTypeCmdMysql) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c DeleteFieldTypeCmdMysql) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c DeleteFieldTypeCmdMysql) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c DeleteFieldTypeCmdMysql) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c DeleteFieldTypeCmdMysql) TableName() string { return "field_types" }

// GetID returns the fieldType ID for this command.
func (c DeleteFieldTypeCmdMysql) GetID() string { return string(c.id) }

// GetBefore retrieves the fieldType before the delete.
func (c DeleteFieldTypeCmdMysql) GetBefore(ctx context.Context, tx audited.DBTX) (mdbm.FieldTypes, error) {
	queries := mdbm.New(tx)
	return queries.GetFieldTypes(ctx, mdbm.GetFieldTypesParams{FieldTypeID: c.id})
}

// Execute deletes the fieldType from the database.
func (c DeleteFieldTypeCmdMysql) Execute(ctx context.Context, tx audited.DBTX) error {
	queries := mdbm.New(tx)
	return queries.DeleteFieldTypes(ctx, mdbm.DeleteFieldTypesParams{FieldTypeID: c.id})
}

// DeleteFieldTypeCmd creates a command for deleting a fieldType.
func (d MysqlDatabase) DeleteFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, id types.FieldTypeID) DeleteFieldTypeCmdMysql {
	return DeleteFieldTypeCmdMysql{ctx: ctx, auditCtx: auditCtx, id: id, conn: d.Connection, recorder: MysqlRecorder}
}

// ----- PostgreSQL CREATE -----

// NewFieldTypeCmdPsql is an audited command for creating fieldTypes in PostgreSQL.
type NewFieldTypeCmdPsql struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	params   CreateFieldTypeParams
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c NewFieldTypeCmdPsql) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c NewFieldTypeCmdPsql) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c NewFieldTypeCmdPsql) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c NewFieldTypeCmdPsql) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c NewFieldTypeCmdPsql) TableName() string { return "field_types" }

// Params returns the parameters for this command.
func (c NewFieldTypeCmdPsql) Params() any { return c.params }

// GetID extracts the ID from a fieldType record.
func (c NewFieldTypeCmdPsql) GetID(u mdbp.FieldTypes) string { return string(u.FieldTypeID) }

// Execute creates the fieldType in the database.
func (c NewFieldTypeCmdPsql) Execute(ctx context.Context, tx audited.DBTX) (mdbp.FieldTypes, error) {
	queries := mdbp.New(tx)
	return queries.CreateFieldTypes(ctx, mdbp.CreateFieldTypesParams{
		FieldTypeID: types.NewFieldTypeID(),
		Type:        c.params.Type,
		Label:       c.params.Label,
	})
}

// NewFieldTypeCmd creates a command for inserting a fieldType.
func (d PsqlDatabase) NewFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, params CreateFieldTypeParams) NewFieldTypeCmdPsql {
	return NewFieldTypeCmdPsql{ctx: ctx, auditCtx: auditCtx, params: params, conn: d.Connection, recorder: PsqlRecorder}
}

// ----- PostgreSQL UPDATE -----

// UpdateFieldTypeCmdPsql is an audited command for updating fieldTypes in PostgreSQL.
type UpdateFieldTypeCmdPsql struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	params   UpdateFieldTypeParams
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c UpdateFieldTypeCmdPsql) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c UpdateFieldTypeCmdPsql) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c UpdateFieldTypeCmdPsql) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c UpdateFieldTypeCmdPsql) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c UpdateFieldTypeCmdPsql) TableName() string { return "field_types" }

// Params returns the parameters for this command.
func (c UpdateFieldTypeCmdPsql) Params() any { return c.params }

// GetID returns the fieldType ID for this command.
func (c UpdateFieldTypeCmdPsql) GetID() string { return string(c.params.FieldTypeID) }

// GetBefore retrieves the fieldType before the update.
func (c UpdateFieldTypeCmdPsql) GetBefore(ctx context.Context, tx audited.DBTX) (mdbp.FieldTypes, error) {
	queries := mdbp.New(tx)
	return queries.GetFieldTypes(ctx, mdbp.GetFieldTypesParams{FieldTypeID: c.params.FieldTypeID})
}

// Execute updates the fieldType in the database.
func (c UpdateFieldTypeCmdPsql) Execute(ctx context.Context, tx audited.DBTX) error {
	queries := mdbp.New(tx)
	return queries.UpdateFieldTypes(ctx, mdbp.UpdateFieldTypesParams{
		Type:        c.params.Type,
		Label:       c.params.Label,
		FieldTypeID: c.params.FieldTypeID,
	})
}

// UpdateFieldTypeCmd creates a command for updating a fieldType.
func (d PsqlDatabase) UpdateFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, params UpdateFieldTypeParams) UpdateFieldTypeCmdPsql {
	return UpdateFieldTypeCmdPsql{ctx: ctx, auditCtx: auditCtx, params: params, conn: d.Connection, recorder: PsqlRecorder}
}

// ----- PostgreSQL DELETE -----

// DeleteFieldTypeCmdPsql is an audited command for deleting fieldTypes in PostgreSQL.
type DeleteFieldTypeCmdPsql struct {
	ctx      context.Context
	auditCtx audited.AuditContext
	id       types.FieldTypeID
	conn     *sql.DB
	recorder audited.ChangeEventRecorder
}

// Context returns the command context.
func (c DeleteFieldTypeCmdPsql) Context() context.Context { return c.ctx }

// AuditContext returns the audit context.
func (c DeleteFieldTypeCmdPsql) AuditContext() audited.AuditContext { return c.auditCtx }

// Connection returns the database connection.
func (c DeleteFieldTypeCmdPsql) Connection() *sql.DB { return c.conn }

// Recorder returns the change event recorder.
func (c DeleteFieldTypeCmdPsql) Recorder() audited.ChangeEventRecorder { return c.recorder }

// TableName returns the table name for this command.
func (c DeleteFieldTypeCmdPsql) TableName() string { return "field_types" }

// GetID returns the fieldType ID for this command.
func (c DeleteFieldTypeCmdPsql) GetID() string { return string(c.id) }

// GetBefore retrieves the fieldType before the delete.
func (c DeleteFieldTypeCmdPsql) GetBefore(ctx context.Context, tx audited.DBTX) (mdbp.FieldTypes, error) {
	queries := mdbp.New(tx)
	return queries.GetFieldTypes(ctx, mdbp.GetFieldTypesParams{FieldTypeID: c.id})
}

// Execute deletes the fieldType from the database.
func (c DeleteFieldTypeCmdPsql) Execute(ctx context.Context, tx audited.DBTX) error {
	queries := mdbp.New(tx)
	return queries.DeleteFieldTypes(ctx, mdbp.DeleteFieldTypesParams{FieldTypeID: c.id})
}

// DeleteFieldTypeCmd creates a command for deleting a fieldType.
func (d PsqlDatabase) DeleteFieldTypeCmd(ctx context.Context, auditCtx audited.AuditContext, id types.FieldTypeID) DeleteFieldTypeCmdPsql {
	return DeleteFieldTypeCmdPsql{ctx: ctx, auditCtx: auditCtx, id: id, conn: d.Connection, recorder: PsqlRecorder}
}
