// Code generated by tools/dbgen; DO NOT EDIT.
package db

import (
	"fmt"

	mdbm "github.com/hegner123/modulacms/internal/db-mysql"
	mdbp "github.com/hegner123/modulacms/internal/db-psql"
	mdb "github.com/hegner123/modulacms/internal/db-sqlite"
	"github.com/hegner123/modulacms/internal/utility"
)

///////////////////////////////
// STRUCTS
//////////////////////////////

// MediaDimensions represents a mediaDimension record in the database.
type MediaDimensions struct {
	MdID        string     `json:"md_id"`
	Label       NullString `json:"label"`
	Width       NullInt64  `json:"width"`
	Height      NullInt64  `json:"height"`
	AspectRatio NullString `json:"aspect_ratio"`
}

// CreateMediaDimensionParams contains parameters for creating a new mediaDimension.
type CreateMediaDimensionParams struct {
	Label       NullString `json:"label"`
	Width       NullInt64  `json:"width"`
	Height      NullInt64  `json:"height"`
	AspectRatio NullString `json:"aspect_ratio"`
}

// UpdateMediaDimensionParams contains parameters for updating an existing mediaDimension.
type UpdateMediaDimensionParams struct {
	Label       NullString `json:"label"`
	Width       NullInt64  `json:"width"`
	Height      NullInt64  `json:"height"`
	AspectRatio NullString `json:"aspect_ratio"`
	MdID        string     `json:"md_id"`
}

// MapStringMediaDimension converts MediaDimensions to StringMediaDimensions for TUI display.
func MapStringMediaDimension(a MediaDimensions) StringMediaDimensions {
	return StringMediaDimensions{
		MdID:        a.MdID,
		Label:       utility.NullToString(a.Label.NullString),
		Width:       utility.NullToString(a.Width.NullInt64),
		Height:      utility.NullToString(a.Height.NullInt64),
		AspectRatio: utility.NullToString(a.AspectRatio.NullString),
	}
}

///////////////////////////////
// SQLITE
//////////////////////////////

// QUERIES

// CountMediaDimensions returns the total number of mediaDimensions in the database.
func (d Database) CountMediaDimensions() (*int64, error) {
	queries := mdb.New(d.Connection)
	c, err := queries.CountMediaDimension(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateMediaDimensionTable creates the media_dimensions table in the database.
func (d Database) CreateMediaDimensionTable() error {
	queries := mdb.New(d.Connection)
	err := queries.CreateMediaDimensionTable(d.Context)
	return err
}

// GetMediaDimension retrieves a mediaDimension by ID.
func (d Database) GetMediaDimension(id string) (*MediaDimensions, error) {
	queries := mdb.New(d.Connection)
	row, err := queries.GetMediaDimension(d.Context, mdb.GetMediaDimensionParams{MdID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapMediaDimension(row)
	return &res, nil
}

// ListMediaDimensions retrieves all mediaDimensions in the database.
func (d Database) ListMediaDimensions() (*[]MediaDimensions, error) {
	queries := mdb.New(d.Connection)
	rows, err := queries.ListMediaDimension(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get MediaDimensions: %v\n", err)
	}
	res := []MediaDimensions{}
	for _, v := range rows {
		m := d.MapMediaDimension(v)
		res = append(res, m)
	}
	return &res, nil
}

///////////////////////////////
// MYSQL
//////////////////////////////

// QUERIES

// CountMediaDimensions returns the total number of mediaDimensions in the database.
func (d MysqlDatabase) CountMediaDimensions() (*int64, error) {
	queries := mdbm.New(d.Connection)
	c, err := queries.CountMediaDimension(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateMediaDimensionTable creates the media_dimensions table in the database.
func (d MysqlDatabase) CreateMediaDimensionTable() error {
	queries := mdbm.New(d.Connection)
	err := queries.CreateMediaDimensionTable(d.Context)
	return err
}

// GetMediaDimension retrieves a mediaDimension by ID.
func (d MysqlDatabase) GetMediaDimension(id string) (*MediaDimensions, error) {
	queries := mdbm.New(d.Connection)
	row, err := queries.GetMediaDimension(d.Context, mdbm.GetMediaDimensionParams{MdID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapMediaDimension(row)
	return &res, nil
}

// ListMediaDimensions retrieves all mediaDimensions in the database.
func (d MysqlDatabase) ListMediaDimensions() (*[]MediaDimensions, error) {
	queries := mdbm.New(d.Connection)
	rows, err := queries.ListMediaDimension(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get MediaDimensions: %v\n", err)
	}
	res := []MediaDimensions{}
	for _, v := range rows {
		m := d.MapMediaDimension(v)
		res = append(res, m)
	}
	return &res, nil
}

///////////////////////////////
// POSTGRES
//////////////////////////////

// QUERIES

// CountMediaDimensions returns the total number of mediaDimensions in the database.
func (d PsqlDatabase) CountMediaDimensions() (*int64, error) {
	queries := mdbp.New(d.Connection)
	c, err := queries.CountMediaDimension(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateMediaDimensionTable creates the media_dimensions table in the database.
func (d PsqlDatabase) CreateMediaDimensionTable() error {
	queries := mdbp.New(d.Connection)
	err := queries.CreateMediaDimensionTable(d.Context)
	return err
}

// GetMediaDimension retrieves a mediaDimension by ID.
func (d PsqlDatabase) GetMediaDimension(id string) (*MediaDimensions, error) {
	queries := mdbp.New(d.Connection)
	row, err := queries.GetMediaDimension(d.Context, mdbp.GetMediaDimensionParams{MdID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapMediaDimension(row)
	return &res, nil
}

// ListMediaDimensions retrieves all mediaDimensions in the database.
func (d PsqlDatabase) ListMediaDimensions() (*[]MediaDimensions, error) {
	queries := mdbp.New(d.Connection)
	rows, err := queries.ListMediaDimension(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get MediaDimensions: %v\n", err)
	}
	res := []MediaDimensions{}
	for _, v := range rows {
		m := d.MapMediaDimension(v)
		res = append(res, m)
	}
	return &res, nil
}
