// Code generated by tools/dbgen; DO NOT EDIT.
package db

import (
	"fmt"

	mdbm "github.com/hegner123/modulacms/internal/db-mysql"
	mdbp "github.com/hegner123/modulacms/internal/db-psql"
	mdb "github.com/hegner123/modulacms/internal/db-sqlite"
	"github.com/hegner123/modulacms/internal/db/types"
)

///////////////////////////////
// STRUCTS
//////////////////////////////

// UserOauth represents a userOauth record in the database.
type UserOauth struct {
	UserOauthID         types.UserOauthID    `json:"user_oauth_id"`
	UserID              types.NullableUserID `json:"user_id"`
	OauthProvider       string               `json:"oauth_provider"`
	OauthProviderUserID string               `json:"oauth_provider_user_id"`
	AccessToken         string               `json:"access_token"`
	RefreshToken        string               `json:"refresh_token"`
	TokenExpiresAt      string               `json:"token_expires_at"`
	DateCreated         types.Timestamp      `json:"date_created"`
}

// CreateUserOauthParams contains parameters for creating a new userOauth.
type CreateUserOauthParams struct {
	UserID              types.NullableUserID `json:"user_id"`
	OauthProvider       string               `json:"oauth_provider"`
	OauthProviderUserID string               `json:"oauth_provider_user_id"`
	AccessToken         string               `json:"access_token"`
	RefreshToken        string               `json:"refresh_token"`
	TokenExpiresAt      string               `json:"token_expires_at"`
	DateCreated         types.Timestamp      `json:"date_created"`
}

// UpdateUserOauthParams contains parameters for updating an existing userOauth.
type UpdateUserOauthParams struct {
	AccessToken    string            `json:"access_token"`
	RefreshToken   string            `json:"refresh_token"`
	TokenExpiresAt string            `json:"token_expires_at"`
	UserOauthID    types.UserOauthID `json:"user_oauth_id"`
}

// MapStringUserOauth converts UserOauth to StringUserOauth for TUI display.
func MapStringUserOauth(a UserOauth) StringUserOauth {
	return StringUserOauth{
		UserOauthID:         a.UserOauthID.String(),
		UserID:              a.UserID.String(),
		OauthProvider:       a.OauthProvider,
		OauthProviderUserID: a.OauthProviderUserID,
		AccessToken:         a.AccessToken,
		RefreshToken:        a.RefreshToken,
		TokenExpiresAt:      a.TokenExpiresAt,
		DateCreated:         a.DateCreated.String(),
	}
}

///////////////////////////////
// SQLITE
//////////////////////////////

// QUERIES

// CountUserOauths returns the total number of userOauths in the database.
func (d Database) CountUserOauths() (*int64, error) {
	queries := mdb.New(d.Connection)
	c, err := queries.CountUserOauths(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateUserOauthTable creates the user_oauth table in the database.
func (d Database) CreateUserOauthTable() error {
	queries := mdb.New(d.Connection)
	err := queries.CreateUserOauthTable(d.Context)
	return err
}

// ListUserOauths retrieves all userOauths in the database.
func (d Database) ListUserOauths() (*[]UserOauth, error) {
	queries := mdb.New(d.Connection)
	rows, err := queries.ListUserOauth(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get UserOauth: %v\n", err)
	}
	res := []UserOauth{}
	for _, v := range rows {
		m := d.MapUserOauth(v)
		res = append(res, m)
	}
	return &res, nil
}

// GetUserOauthByUserId retrieves a userOauth by userID.
func (d Database) GetUserOauthByUserId(userID types.NullableUserID) (*UserOauth, error) {
	queries := mdb.New(d.Connection)
	row, err := queries.GetUserOauthByUserId(d.Context, mdb.GetUserOauthByUserIdParams{UserID: userID})
	if err != nil {
		return nil, err
	}
	res := d.MapUserOauth(row)
	return &res, nil
}

// GetUserOauthByProviderID retrieves a userOauth by provider.
func (d Database) GetUserOauthByProviderID(provider string, providerUserID string) (*UserOauth, error) {
	queries := mdb.New(d.Connection)
	row, err := queries.GetUserOauthByProviderID(d.Context, mdb.GetUserOauthByProviderIDParams{OauthProvider: provider, OAuthProviderUserID: providerUserID})
	if err != nil {
		return nil, err
	}
	res := d.MapUserOauth(row)
	return &res, nil
}

///////////////////////////////
// MYSQL
//////////////////////////////

// QUERIES

// CountUserOauths returns the total number of userOauths in the database.
func (d MysqlDatabase) CountUserOauths() (*int64, error) {
	queries := mdbm.New(d.Connection)
	c, err := queries.CountUserOauths(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateUserOauthTable creates the user_oauth table in the database.
func (d MysqlDatabase) CreateUserOauthTable() error {
	queries := mdbm.New(d.Connection)
	err := queries.CreateUserOauthTable(d.Context)
	return err
}

// ListUserOauths retrieves all userOauths in the database.
func (d MysqlDatabase) ListUserOauths() (*[]UserOauth, error) {
	queries := mdbm.New(d.Connection)
	rows, err := queries.ListUserOauth(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get UserOauth: %v\n", err)
	}
	res := []UserOauth{}
	for _, v := range rows {
		m := d.MapUserOauth(v)
		res = append(res, m)
	}
	return &res, nil
}

// GetUserOauthByUserId retrieves a userOauth by userID.
func (d MysqlDatabase) GetUserOauthByUserId(userID types.NullableUserID) (*UserOauth, error) {
	queries := mdbm.New(d.Connection)
	row, err := queries.GetUserOauthByUserId(d.Context, mdbm.GetUserOauthByUserIdParams{UserID: userID})
	if err != nil {
		return nil, err
	}
	res := d.MapUserOauth(row)
	return &res, nil
}

// GetUserOauthByProviderID retrieves a userOauth by provider.
func (d MysqlDatabase) GetUserOauthByProviderID(provider string, providerUserID string) (*UserOauth, error) {
	queries := mdbm.New(d.Connection)
	row, err := queries.GetUserOauthByProviderID(d.Context, mdbm.GetUserOauthByProviderIDParams{OauthProvider: provider, OAuthProviderUserID: providerUserID})
	if err != nil {
		return nil, err
	}
	res := d.MapUserOauth(row)
	return &res, nil
}

///////////////////////////////
// POSTGRES
//////////////////////////////

// QUERIES

// CountUserOauths returns the total number of userOauths in the database.
func (d PsqlDatabase) CountUserOauths() (*int64, error) {
	queries := mdbp.New(d.Connection)
	c, err := queries.CountUserOauths(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateUserOauthTable creates the user_oauth table in the database.
func (d PsqlDatabase) CreateUserOauthTable() error {
	queries := mdbp.New(d.Connection)
	err := queries.CreateUserOauthTable(d.Context)
	return err
}

// ListUserOauths retrieves all userOauths in the database.
func (d PsqlDatabase) ListUserOauths() (*[]UserOauth, error) {
	queries := mdbp.New(d.Connection)
	rows, err := queries.ListUserOauth(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get UserOauth: %v\n", err)
	}
	res := []UserOauth{}
	for _, v := range rows {
		m := d.MapUserOauth(v)
		res = append(res, m)
	}
	return &res, nil
}

// GetUserOauthByUserId retrieves a userOauth by userID.
func (d PsqlDatabase) GetUserOauthByUserId(userID types.NullableUserID) (*UserOauth, error) {
	queries := mdbp.New(d.Connection)
	row, err := queries.GetUserOauthByUserId(d.Context, mdbp.GetUserOauthByUserIdParams{UserID: userID})
	if err != nil {
		return nil, err
	}
	res := d.MapUserOauth(row)
	return &res, nil
}

// GetUserOauthByProviderID retrieves a userOauth by provider.
func (d PsqlDatabase) GetUserOauthByProviderID(provider string, providerUserID string) (*UserOauth, error) {
	queries := mdbp.New(d.Connection)
	row, err := queries.GetUserOauthByProviderID(d.Context, mdbp.GetUserOauthByProviderIDParams{OauthProvider: provider, OAuthProviderUserID: providerUserID})
	if err != nil {
		return nil, err
	}
	res := d.MapUserOauth(row)
	return &res, nil
}
