// Code generated by tools/dbgen; DO NOT EDIT.
package db

import (
	"fmt"

	mdbm "github.com/hegner123/modulacms/internal/db-mysql"
	mdbp "github.com/hegner123/modulacms/internal/db-psql"
	mdb "github.com/hegner123/modulacms/internal/db-sqlite"
	"github.com/hegner123/modulacms/internal/db/types"
)

///////////////////////////////
// STRUCTS
//////////////////////////////

// WebhookDelivery represents a webhookDelivery record in the database.
type WebhookDelivery struct {
	DeliveryID     types.WebhookDeliveryID `json:"delivery_id"`
	WebhookID      types.WebhookID         `json:"webhook_id"`
	Event          string                  `json:"event"`
	Payload        string                  `json:"payload"`
	Status         string                  `json:"status"`
	Attempts       int64                   `json:"attempts"`
	LastStatusCode int64                   `json:"last_status_code"`
	LastError      string                  `json:"last_error"`
	NextRetryAt    string                  `json:"next_retry_at"`
	CreatedAt      types.Timestamp         `json:"created_at"`
	CompletedAt    string                  `json:"completed_at"`
}

// CreateWebhookDeliveryParams contains parameters for creating a new webhookDelivery.
type CreateWebhookDeliveryParams struct {
	WebhookID types.WebhookID `json:"webhook_id"`
	Event     string          `json:"event"`
	Payload   string          `json:"payload"`
	Status    string          `json:"status"`
	Attempts  int64           `json:"attempts"`
	CreatedAt types.Timestamp `json:"created_at"`
}

// UpdateWebhookDeliveryParams contains parameters for updating an existing webhookDelivery.
type UpdateWebhookDeliveryParams struct {
	Status         string                  `json:"status"`
	Attempts       int64                   `json:"attempts"`
	LastStatusCode int64                   `json:"last_status_code"`
	LastError      string                  `json:"last_error"`
	NextRetryAt    string                  `json:"next_retry_at"`
	CompletedAt    string                  `json:"completed_at"`
	DeliveryID     types.WebhookDeliveryID `json:"delivery_id"`
}

///////////////////////////////
// SQLITE
//////////////////////////////

// QUERIES

// CountWebhookDeliveries returns the total number of webhookDeliveries in the database.
func (d Database) CountWebhookDeliveries() (*int64, error) {
	queries := mdb.New(d.Connection)
	c, err := queries.CountWebhookDelivery(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateWebhookDeliveryTable creates the webhook_deliveries table in the database.
func (d Database) CreateWebhookDeliveryTable() error {
	queries := mdb.New(d.Connection)
	err := queries.CreateWebhookDeliveryTable(d.Context)
	return err
}

// GetWebhookDelivery retrieves a webhookDelivery by ID.
func (d Database) GetWebhookDelivery(id types.WebhookDeliveryID) (*WebhookDelivery, error) {
	queries := mdb.New(d.Connection)
	row, err := queries.GetWebhookDelivery(d.Context, mdb.GetWebhookDeliveryParams{DeliveryID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapWebhookDelivery(row)
	return &res, nil
}

// ListWebhookDeliveries retrieves all webhookDeliveries in the database.
func (d Database) ListWebhookDeliveries() (*[]WebhookDelivery, error) {
	queries := mdb.New(d.Connection)
	rows, err := queries.ListWebhookDeliveries(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get WebhookDelivery: %v\n", err)
	}
	res := []WebhookDelivery{}
	for _, v := range rows {
		m := d.MapWebhookDelivery(v)
		res = append(res, m)
	}
	return &res, nil
}

// ListWebhookDeliveriesByWebhook retrieves webhookDeliveries by webhookID.
func (d Database) ListWebhookDeliveriesByWebhook(webhookID types.WebhookID) (*[]WebhookDelivery, error) {
	queries := mdb.New(d.Connection)
	rows, err := queries.ListWebhookDeliveriesByWebhook(d.Context, mdb.ListWebhookDeliveriesByWebhookParams{WebhookID: webhookID})
	if err != nil {
		return nil, fmt.Errorf("failed to get WebhookDelivery by webhookID: %v\n", err)
	}
	res := []WebhookDelivery{}
	for _, v := range rows {
		m := d.MapWebhookDelivery(v)
		res = append(res, m)
	}
	return &res, nil
}

///////////////////////////////
// MYSQL
//////////////////////////////

// QUERIES

// CountWebhookDeliveries returns the total number of webhookDeliveries in the database.
func (d MysqlDatabase) CountWebhookDeliveries() (*int64, error) {
	queries := mdbm.New(d.Connection)
	c, err := queries.CountWebhookDelivery(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateWebhookDeliveryTable creates the webhook_deliveries table in the database.
func (d MysqlDatabase) CreateWebhookDeliveryTable() error {
	queries := mdbm.New(d.Connection)
	err := queries.CreateWebhookDeliveryTable(d.Context)
	return err
}

// GetWebhookDelivery retrieves a webhookDelivery by ID.
func (d MysqlDatabase) GetWebhookDelivery(id types.WebhookDeliveryID) (*WebhookDelivery, error) {
	queries := mdbm.New(d.Connection)
	row, err := queries.GetWebhookDelivery(d.Context, mdbm.GetWebhookDeliveryParams{DeliveryID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapWebhookDelivery(row)
	return &res, nil
}

// ListWebhookDeliveries retrieves all webhookDeliveries in the database.
func (d MysqlDatabase) ListWebhookDeliveries() (*[]WebhookDelivery, error) {
	queries := mdbm.New(d.Connection)
	rows, err := queries.ListWebhookDeliveries(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get WebhookDelivery: %v\n", err)
	}
	res := []WebhookDelivery{}
	for _, v := range rows {
		m := d.MapWebhookDelivery(v)
		res = append(res, m)
	}
	return &res, nil
}

// ListWebhookDeliveriesByWebhook retrieves webhookDeliveries by webhookID.
func (d MysqlDatabase) ListWebhookDeliveriesByWebhook(webhookID types.WebhookID) (*[]WebhookDelivery, error) {
	queries := mdbm.New(d.Connection)
	rows, err := queries.ListWebhookDeliveriesByWebhook(d.Context, mdbm.ListWebhookDeliveriesByWebhookParams{WebhookID: webhookID})
	if err != nil {
		return nil, fmt.Errorf("failed to get WebhookDelivery by webhookID: %v\n", err)
	}
	res := []WebhookDelivery{}
	for _, v := range rows {
		m := d.MapWebhookDelivery(v)
		res = append(res, m)
	}
	return &res, nil
}

///////////////////////////////
// POSTGRES
//////////////////////////////

// QUERIES

// CountWebhookDeliveries returns the total number of webhookDeliveries in the database.
func (d PsqlDatabase) CountWebhookDeliveries() (*int64, error) {
	queries := mdbp.New(d.Connection)
	c, err := queries.CountWebhookDelivery(d.Context)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}
	return &c, nil
}

// CreateWebhookDeliveryTable creates the webhook_deliveries table in the database.
func (d PsqlDatabase) CreateWebhookDeliveryTable() error {
	queries := mdbp.New(d.Connection)
	err := queries.CreateWebhookDeliveryTable(d.Context)
	return err
}

// GetWebhookDelivery retrieves a webhookDelivery by ID.
func (d PsqlDatabase) GetWebhookDelivery(id types.WebhookDeliveryID) (*WebhookDelivery, error) {
	queries := mdbp.New(d.Connection)
	row, err := queries.GetWebhookDelivery(d.Context, mdbp.GetWebhookDeliveryParams{DeliveryID: id})
	if err != nil {
		return nil, err
	}
	res := d.MapWebhookDelivery(row)
	return &res, nil
}

// ListWebhookDeliveries retrieves all webhookDeliveries in the database.
func (d PsqlDatabase) ListWebhookDeliveries() (*[]WebhookDelivery, error) {
	queries := mdbp.New(d.Connection)
	rows, err := queries.ListWebhookDeliveries(d.Context)
	if err != nil {
		return nil, fmt.Errorf("failed to get WebhookDelivery: %v\n", err)
	}
	res := []WebhookDelivery{}
	for _, v := range rows {
		m := d.MapWebhookDelivery(v)
		res = append(res, m)
	}
	return &res, nil
}

// ListWebhookDeliveriesByWebhook retrieves webhookDeliveries by webhookID.
func (d PsqlDatabase) ListWebhookDeliveriesByWebhook(webhookID types.WebhookID) (*[]WebhookDelivery, error) {
	queries := mdbp.New(d.Connection)
	rows, err := queries.ListWebhookDeliveriesByWebhook(d.Context, mdbp.ListWebhookDeliveriesByWebhookParams{WebhookID: webhookID})
	if err != nil {
		return nil, fmt.Errorf("failed to get WebhookDelivery by webhookID: %v\n", err)
	}
	res := []WebhookDelivery{}
	for _, v := range rows {
		m := d.MapWebhookDelivery(v)
		res = append(res, m)
	}
	return &res, nil
}
