CREATE TABLE admin_field (
    admin_field_id INTEGER PRIMARY KEY,
    adminrouteid INTEGER NOT NULL DEFAULT 1,
    parentid INTEGER NOT NULL DEFAULT 1,
    label TEXT NOT NULL DEFAULT "unlabeled",
    data TEXT NOT NULL DEFAULT "",
    type TEXT NOT NULL DEFAULT "text",
    author TEXT NOT NULL DEFAULT "system",
    authorid INTEGER NOT NULL DEFAULT 1,
    datecreated TEXT NOT NULL DEFAULT LOCALTIMESTAMP,
    datemodified TEXT DEFAULT LOCALTIMESTAMP,
    FOREIGN KEY (author) REFERENCES user(username) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (authorid) REFERENCES user(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (adminrouteid) REFERENCES adminroute(admin_route_id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    FOREIGN KEY (parentid) REFERENCES admin_datatype(admin_dt_id) ON DELETE SET DEFAULT ON UPDATE CASCADE
);
